### ISSUE TITLE
Spectre

### ISSUE THREAD

**Issue by tomashhurst** [DataBiosphere/data-portal#1021]
Thank you for submitting a method package to the HCA DCP Analysis Tools Registry!

To expedite your package's addition to https://data.humancellatlas.org/analyze/methods,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your package's detail page ([example](https://data.humancellatlas.org/analyze/methods/stream)).

[Required](https://data.humancellatlas.org/contribute/analysis-tools-registry#package-submission-field-details):
- Tool title: Spectre
- Contact name: Thomas Ashhurst
- Contact email: thomas.ashhurst@sydney.edu.au
- Who to attribute: Thomas Ashhurst, Felix Marsh-Wakefield, Givanna Putri
- Method-ready Docker image URL: https://hub.docker.com/r/immunedynamics/spectre
- Code repository URL: https://github.com/ImmuneDynamics/Spectre
- Affirm code is free and open source with license available in code repository: [X]
- Language: English
- Upstream registry URL: placeholder
- Test data location: within package
- Basic command line usage: Extensive command line usage in R or RStudio provided at [https://immunedynamics.github.io/spectre/](https://immunedynamics.github.io/spectre/)
- Command to validate installation: package.check()
- Short description: Spectre is an R package and computational toolkit that enables comprehensive end-to-end integration, exploration, and analysis of high-dimensional cytometry or imaging data.

[Optional](https://data.humancellatlas.org/contribute/analysis-tools-registry#optional-fields-for-methods-and-visualizations):
- Long description: Overview: Spectre is an R package and computational toolkit that enables comprehensive end-to-end integration, exploration, and analysis of high-dimensional cytometry or imaging data from different batches or experiments. Spectre streamlines the analytical stages of raw data pre-processing, batch alignment, data integration, clustering, dimensionality reduction, visualisation and population labelling, as well as quantitative and statistical analysis; with a simple, clear, and modular design of analysis workflows, that can be utilised by data and laboratory scientists. For users unfamiliar with using R, we also provide workflow instructions for replicating many of our analysis approaches in programs such as FlowJo.
- Build badge URL: https://camo.githubusercontent.com/e778875bb2f2b2aa0bcf9e842d1a5d4a97e6185a02c4b3118d286b39364e2dcf/68747470733a2f2f63692e6170707665796f722e636f6d2f6170692f70726f6a656374732f7374617475732f616b68766238777562366436786874643f7376673d74727565
- Coverage badge URL: 
- Logo: 
![Spectre](https://user-images.githubusercontent.com/11766139/126143602-908c8cc5-7779-4bd7-bd48-289cb0d55c8a.png)

- Screenshot: (attach to this GitHub issue)
- Implementation of this tool in an active portal:
- Benchmark dataset:

**Comment by NoopDog** [comment]
Hi @tomashhurst thank you for the submission to the methods registry. We will review and let you know if we have any questions or comments in the next week or so.

**Comment by NoopDog** [comment]
Hi @tomashhurst

Thanks for submitting your tool to the Analysis Tools Registry.

Your application has been approved and your tool now lists here:

https://data.humancellatlas.org/analyze/methods/spectre

Please feel free to make a pull request using the "Improve this page" button at the bottom of the Spectre page if you would like any of the content to be updated.

Cheers
Dave Rogers

**Comment by tomashhurst** [comment]
Thanks @NoopDog !
