### ISSUE TITLE
Increase the visibility of the "submit your portal" option

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#1025]
The "submit" is a bit hidden in the text below we could improve this by using a button instead of the link and possibly giving its own heading or brighter background.

Do this for all three sections. Analysis Portals, Methods Packages, Visualization Packages.

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/8561ac7b-0634-4846-a22b-8939f57d20c0)

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
