### ISSUE TITLE
Add Terra to the analysis portals section

### ISSUE THREAD

**Issue by asagoffbroad** [DataBiosphere/data-portal#1053]
Thank you for submitting a portal to the HCA DCP Methods Registry!

To expedite your portal's addition to https://data.humancellatlas.org/analyze,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your portal's detail page ([example](https://data.humancellatlas.org/analyze/portals/asap)).

Required:
- Tool title: Terra
- Contact name: 
- Contact email: support@terra.bio
- Who to attribute: Broad Institute, Microsoft, and Verily
- Portal URL: https://app.terra.bio/
- Short description: (<= 200 characters, will appear on list page)

Terra is a secure, scalable, open-source platform for biomedical researchers to access data, run analysis tools and collaborate.

Optional:
- Long description: (will appear on detail page)
- Logo or screenshot: (attach to this GitHub issue.)

Terra is a scalable, open-source platform for biomedical researchers to access data, run analysis tools, and collaborate securely in the cloud. It powers important scientific projects including NHGRI’s AnVIL, NHLBI’s BioData Catalyst, Human Cell Atlas, the BRAIN Initiative Cell Census Network, and many others. Terra provides easy access to both open and access-controlled datasets hosted in cloud repositories.You can explore, analyze, and visualize data using Jupyter Notebooks, RStudio, RShinyApps, and Galaxy. You can also run your own bioinformatics workflows at scale or try community favorites. Secure workspaces allow you to easily share your work with collaborators.

You can access HCA data in Data Coordination Platform’s (DCP) [Data Portal](https://data.humancellatlas.org/) and easily export this data to Terra for further analysis. Exporting HCA data to Terra is quick and it will not incur additional download costs: 

- Browse the data in the Data Portal’s [Data browser](https://data.humancellatlas.org/explore/projects).
- [Export](https://data.humancellatlas.org/guides/consumer-vignettes/export-to-terra) the selected data to a Terra workspace. 
- Analyze the data using popular single-cell bioinformatics workflows or community tools such as Bioconductor, Cumulus, Pegasus, Scanpy, and Seurat.

To register for a Terra account, follow these [instructions](https://support.terra.bio/hc/en-us/articles/360028235911). After registering, start exploring HCA data in Terra using this [guide](https://data.humancellatlas.org/guides/consumer-vignettes/export-to-terra) or the [Intro-to-HCA-data-on-Terra](https://app.terra.bio/#workspaces/featured-workspaces-hca/Intro-to-HCA-data-on-Terra) workspace [tutorial](https://support.terra.bio/hc/en-us/articles/360060041772). 

To learn more about Terra, visit [terra.bio](https://terra.bio/).  
<img width="692" alt="Screen Shot 2021-08-26 at 1 48 09 PM" src="https://user-images.githubusercontent.com/88785146/131011222-6795edbd-2308-413f-b00b-bd27877954cb.png">

**Comment by NoopDog** [comment]
Hi, @asagoffbroad  thanks for the submissions we will review and let you know if we have any questions.
Cheers, D

**Comment by NoopDog** [comment]
Hi @asagoffbroad The page is created here on the testing site.

https://dev.singlecell.gi.ucsc.edu/analyze/portals/terra

Any feedback before we push this live?

Cheers,
Dave

**Comment by asagoffbroad** [comment]
Great to see this! We will review and get back to you shortly.

**Comment by asagoffbroad** [comment]
One addition if possible: could we add the following image to the top of
the page?
[image: AppTerraHomepage.jpg]

**Comment by NoopDog** [comment]
Hi @asagoffbroad we have reviewed this as well and can push live now.  The AppTerraHomepage.jpg did not come through in this ticket it seems.

Can you make a PR against this page to add?

https://data.humancellatlas.org/analyze/portals/terra

Select the "Improve this page" link at the bottom of the page to edit the page in github.

Cheers,
Dave
