### ISSUE TITLE
Implement Home Page Person Image Hover functionality

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#108]
# Questions

1. Do we have images for female organs?
1. How do we select "skin", "lymph node",  "bone marrow", "hematopoietic system", "cord blood".
1. What are the counts counts of (samples, predicted cells, calculated cells)
1. Where is the hover text for each organ to tell the name (if any)? 
1. can we get an image for bar chart - can make dynamic chart later.
1. Where is spleen any way?
1. join/merge/group large intestine segments so it can be exported as a single organ.
1.  in sketch, the fill's that make up the drawing need to be grouped to organs (to make g tags) and given camel cased html id attribute friendly names. Then we can export the groups and hover etc. 
1. need to consider how this would work on responsive and what this would look like on mobile or should we hide on mobile?
1. what is the order of the bars? Is that ordered by organ name?

regarding the sketch grouping it should be close to this

```
startExploring (group)
    woman (group)
    man (group)
        organName0 (group)
            fill0 (shape)
            fill1 (shape)
            fill2 (shape)
            fill3 (shape)
        organName1 (group)
            fill0 (shape)
            fill1 (shape)
            fill2 (shape)
            fill3 (shape)
    stats (group)
        organName0 (group)
            bar (shape)
            stats (text)
        organName1 (group)
            bar (shape)
            stats (text)
```

**Comment by happyimadesignr** [comment]
Thanks so much for all these questions, super helpful! @NoopDog 

1. Do we have images for female organs?
    1. I think what we need to do is have one set of organs for the pilot and another (adding onto the first) for everything we might expect later on. For the pilot, there was no female specific organs in the data wranglers/ingest spreadsheet.
2. How do we select "skin", "lymph node", "bone marrow", "hematopoietic system", "cord blood".
    1. I’ll might need to create some of these, I'll point it out in pink.
3. What are the counts counts of (samples, predicted cells, calculated cells)
    1. Assigned to me
4. Where is the hover text for each organ to tell the name (if any)?
5. can we get an image for bar chart - can make dynamic chart later. 
    1. Sure
6. Where is spleen any way?
    1. I’ll point out the organs in pink
7. join/merge/group large intestine segments so it can be exported as a single organ.
    1. Ok I’ll take a look
8. in sketch, the fill's that make up the drawing need to be grouped to organs (to make g tags) and given camel cased html id attribute friendly names. Then we can export the groups and hover etc.
    1. What does this mean?
9. need to consider how this would work on responsive and what this would look like on mobile or should we hide on mobile?
    1. Let’s discuss this
10. what is the order of the bars? Is that ordered by organ name?
    1. Yes, alphabetically by organ name
