### ISSUE TITLE
Teams create outlines for their portal content

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-portal#11]
TBD- create a list of teams that need to do this

**Comment by kozbo** [comment]
Hi @jodihir I think that you are already coordinating this. Can we touch base to put together a checklist here to provide visibility

**Comment by jodihir** [comment]
Yes. Does Tuesday afternoon work for you? I'm free at 1PM EST or after 3PM EST.

**Comment by theathorn** [comment]
What's the current status on this?

**Comment by kozbo** [comment]
Outlines are complete. Working on content now.

**Comment by kozbo** [comment]
Reopening:
We need to confirm that we have the correct topic lists in the outlines.

**Comment by NoopDog** [comment]
moved to content repo
