### ISSUE TITLE
Remove "Organs" from landing page summary

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#1139]
John Randell: Specifically regarding the statistics figure on the data portal, could we simply remove "Organs" for the time being, leaving Cells, Donors, Projects, and Labs?

**Comment by NoopDog** [comment]
@theathorn this is on prod. We also removed the link to "more organs" and the word "organ" search box hint text. e.g. it used to say "Filter projects by attribute e.g. organ, project title. Now it says "Filter project by attribute e.g. project title."
