### ISSUE TITLE
Add "Guides" section to LungMAP

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#1156]
Review / repurpose content to make it less HCA specific or standalone in the new context.  

"Exploring Projects" - remove references to HCA DCP and DCP-generated matrices (for now)
"Accessing HCA Data and Metadata" - remove references to HCA DCP
"Exporting HCA Data to Terra" - remove references to HCA DCP
"Exploring Project Matrices" - remove references to HCA DCP and DCP-generated matrices (for now); keep CGMs

**Comment by MillenniumFalconMechanic** [comment]
Add one-pager with pointer to HCA guides section.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
