### ISSUE TITLE
Design tone of content

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-portal#12]
decide on the tone of the documentation. This can be distributed to content creators, but will definitely be used once the first content comes in.

**Comment by theathorn** [comment]
Jodi, is this done?

**Comment by jodihir** [comment]
No. I think as people start adding content to Github we’ll be able to see how the documentation sounds and whether we need to try to unify the tone or it’s just naturally fine as is. (We just want users to get a consistent message and have a smooth experience using the documentation.)

**Comment by theathorn** [comment]
Move to content repo.

**Comment by NoopDog** [comment]
Moved to content repo
