### ISSUE TITLE
Blue Marble Icon in logo owned by Broad

### ISSUE THREAD

**Issue by happyimadesignr** [DataBiosphere/data-portal#121]
The blue marble or icon in the logo is owned by the Broad. For the preview website, their legal team requested a note call this out. The note is: "The mosaic circle is a trademark of the Human Cell Atlas consortium, registered by Broad Institute and used with permission."

We need to figure out what we'll be doing about this moving forward, as it is not ideal to put this on the Data Portal website.

The issue is that there is no HCA entity that can own any assets so the Broad has taken that on. Jonah has been working on this issue to create an HCA entity. Tim will have info about the Broad legal team's requirements.

@theathorn Can you work with Jonah and Tim on this?

**Comment by theathorn** [comment]
The consensus seems to be to add the above note wherever the logo is shown. Possibly in the box on the top left side of each page or more likely in the black bar at the bottom of the page.

**Comment by happyimadesignr** [comment]
Yikes, we can't do this every time the logo is shown! We need a better solution for this.

https://www.humancellatlas.org/ doesn't have it shown on their website.

Sam S's suggestion is to work with Jonah on this.

**Comment by theathorn** [comment]
Jonah Cool:
We navigated this issue with Broad a while back and based on that (at least for CZI's use), the language proposed is correct. I think it is most common to just put it below the image but open to other ideas/solutions.

Timothy Tickle:
I do not think hiding legal text in a mouseover is going to be an option but we can check with legal. More likely putting it at the bottom of the page may be a solution (as something I believe done as a standard).
Thoughts? We should check with legal either way when they have something to look at.

Jonah Cool:
Like both of Tim's options - if we are worried about things getting cramped, bottom of the page should work fine.

**Comment by theathorn** [comment]
Add marble logo to description in Attributions page
