### ISSUE TITLE
Cambridge Cell Atlas

### ISSUE THREAD

**Issue by alfonsomunozpomer** [DataBiosphere/data-portal#1217]
Thank you for submitting a portal to the HCA DCP Methods Registry!

To expedite your portal's addition to https://data.humancellatlas.org/analyze,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your portal's detail page ([example](https://data.humancellatlas.org/analyze/portals/asap)).

Required:
- Tool title: Cambridge Cell Atlas
- Contact name: Sarah Teichmann, Irene Papatheodorou
- Contact email: sarah.teichmann@sanger.ac.uk, irenep@ebi.ac.uk
- Who to attribute: Wellcome Sanger Institute, European Bioinformatics Institute
- Portal URL: https://www.cambridgecellatlas.org/
- Short description: (<= 200 characters, will appear on list page)
Analysis, visualisation and tools for exploration of single cell RNA-Seq data generated by the Human Cell Atlas initiative, as well as other projects on human tissue.

Optional:
- Long description:
The Cambridge Portal of the Human Cell Atlas is a joint initiative between groups at EMBL-EBI and the Wellcome Sanger Institute. The project analyses, visualises and provides tools for exploration of single cell RNA-Seq data generated by the international Human Cell Atlas initiative, as well as other projects on human tissue. The portal is managed by the Gene Expression Team at EMBL-EBI in collaboration with the Wellcome Sanger Institute Cellular Genetics Programme.

**Comment by NoopDog** [comment]
@alfonsomunozpomer thanks for submitting the portal. We will let you know when this is on the staging site for review.  Will try to this up in the next few days.

**Comment by NoopDog** [comment]
Hi @alfonsomunozpomer The Cambridge Cell Atlas is now listed on our dev server here:

https://dev.singlecell.gi.ucsc.edu/analyze/portals/cambridge-cell-atlas

Can you please take a look and let us know if you feel any modifications are required?

Note you can make any basic modifications in a PR by selecting the "Improve this  Page" link at the bottom of the page.

Cheers, 
Dave Rogers

**Comment by NoopDog** [comment]
Hi @alfonsomunozpomer this page is now live:

https://data.humancellatlas.org/analyze/portals/cambridge-cell-atlas

Please let us know if there are any updates you would like to make.

Cheers,
Dave
