### ISSUE TITLE
What data do we show on the homepage?

### ISSUE THREAD

**Issue by happyimadesignr** [DataBiosphere/data-portal#122]
2 issues with the data we show on the homepage:

1. We are the human cell atlas, we have a human diagram, but the data includes mouse data. SamS thinks this should be a wider discussion with the OC which Jonah can help talk with the OC.

2. We are the healthy HCA, but we also have disease data. The disease data is in the browser, but does that belong on the homepage also? SamS suggested for Trevor to coordinate with Jonah on this item also.

@theathorn Let me know if you have any questions.

**Comment by theathorn** [comment]
Jonah Cool:
Adding a brief section about in the "About the DCP" would be helpful. Laura and Clay worked out a prioritization scheme for ingest - there is so much data out there that this is critical. I'd recommend touching base with them and we can also bring it up with the Scientific leadership. One thing that is important to raise from Laura & Clay's efforts is that normal primary human samples are high priority. So, the answer for the time being is that "select data sets from non-human sources will be accepted but prioritization may vary depending on ingest volume." (or something like that).
