### ISSUE TITLE
Add a help page for accessing project metadata via TDR

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-portal#1225]
Add a help page to instruct users how to:
- Obtain the Google Cloud project ID (e.g. `tdr-fp-c315dee1`) and snapshot name (e.g. `hca_prod_20201120_dcp2___20211101_dcp11`) for a given catalog (e.g. `dcp11`)
- Compose BigQuery queries to obtain the metadata content of entities included in a given project.
- Run BigQuery queries via Cloud Console and bq command-line tool.

**Comment by melainalegaspi** [comment]
@danielsotirhos to ask @NoopDog and @MillenniumFalconMechanic in what form they prefer this contribution to come in.

**Comment by NoopDog** [comment]
Hi @danielsotirhos eventually we will want a markdown file. You can take a look at any of the existing guides as examples:

e.g.
https://github.com/HumanCellAtlas/data-portal/blob/main/content/guides/userguides/exploring-projects.md 

If you would like we add a blank page and hook it up to the navigation in a feature branch to get you started.

Cheers,
D

**Comment by dsotirho-ucsc** [comment]
Hi @NoopDog . A feature branch and blank page would be most appreciated. Thanks!

**Comment by NoopDog** [comment]
Hi, @danielsotirhos your feature branch is `1225-tdr-metadata-guide`. 

The blank page is `accessing-metadata-via-tdr.md` under the /content/guides/userguides directory.

Let us know if you have any questions about formatting or including images etc. 

Cheers,
D

**Comment by NoopDog** [comment]
Hi @danielsotirhos this is now on prod.
https://data.humancellatlas.org/guides/accessing-metadata-via-tdr
Thanks for writing this up!
Cheers,
D

**Comment by theathorn** [comment]
Verified.
