### ISSUE TITLE
Broken links in matrices guide

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-portal#1244]
On the page https://data.humancellatlas.org/guides/consumer-vignettes/matrices under the section `DCP-Generated Matrices` there are three broken links.

> <img width="839" src="https://user-images.githubusercontent.com/46407464/145308427-4081dacc-bc53-44f9-be3e-4c0a5c278108.png">

Link text: `project-level matrices`
Current HREF: `#dcp-project-level-matrices`
Expected HREF: `#dcp-project-level-matrix-overview`

Link text: `library-level matrices`
Current HREF: `#dcp-library-level-matrices`
Expected HREF: `#dcp-library-level-matrix-overview`

Link text: `metrics`
Current HREF: `/pipelines/hca-pipelines/data-processing-pipelines/qc-metrics`
Expected HREF: `/pipelines/qc-metrics`

**Comment by NoopDog** [comment]
Thanks, @danielsotirhos for pointing these out.

**Comment by ekiernan** [comment]
Thanks @danielsotirhos!

**Comment by NoopDog** [comment]
Hi @danielsotirhos this should be fixed on prod. Can you confirm? Thanks! D

**Comment by dsotirho-ucsc** [comment]
Confirmed. Thanks!
