### ISSUE TITLE
HCA logo is not a link on "Explore" pages

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-portal#1254]
The `HUMAN CELL ATLAS DATA PORTAL` logo (top left of page) is a clickable link back to the root page ( https://data.humancellatlas.org/ ) on all pages except the `/explore` pages (e.g. https://data.humancellatlas.org/explore/projects )

![Screen Shot 2021-12-14 at 11 28 31 AM](https://user-images.githubusercontent.com/46407464/146066575-4e6514c5-39fc-4ea2-848c-998c0344d719.png)

**Comment by NoopDog** [comment]
Thanks @danielsotirhos we must have just broken this. Will take a look.
Cheers,
D

**Comment by frano-m** [comment]
Closing issue - moved to Data Browser see https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/humancellatlas/data-browser/2132
