### ISSUE TITLE
Implement Contact page

### ISSUE THREAD

**Issue by happyimadesignr** [DataBiosphere/data-portal#131]
@happyimadesignr completing the design

@frano-m can you help implement?

@jodihir can you help with content?

Here's the WIP design:

![Screen Shot 2018-06-25 at 3.30.36 PM.png](https://images.zenhubusercontent.com/5ab9846b4b5806bc2bcc80e2/b5c73059-983b-41d1-8c8f-196fd778fc0d)

**Comment by jodihir** [comment]
I can help - let's discuss what's needed.

**Comment by happyimadesignr** [comment]
https://chanzuckerberg.invisionapp.com/share/QMM7DWKU6ZN#/305992561_1-5_Contact new designs here. Contact is 2 pages. Adrienne and Gabby can help also.

**Comment by happyimadesignr** [comment]
@adriennes has sent this out to the PMs for review!

**Comment by theathorn** [comment]
Contact page mock: https://chanzuckerberg.invisionapp.com/share/B8M7GFUXJGS#/screens/305992561
