### ISSUE TITLE
Move "About" link to the top nav

### ISSUE THREAD

**Issue by happyimadesignr** [DataBiosphere/data-portal#132]
![Screen Shot 2018-06-25 at 3.47.51 PM.png](https://images.zenhubusercontent.com/5ab9846b4b5806bc2bcc80e2/5a0a304a-c5c2-4b78-9469-409beb188573)

**Comment by frano-m** [comment]
@happyimadesignr
1) would you like the About link in the footer to be removed?
2) should the about link in header also be replicated in the browser?
