### ISSUE TITLE
Data flow diagram

### ISSUE THREAD

**Issue by happyimadesignr** [DataBiosphere/data-portal#135]
@jodihir and @kozbo

**Comment by kozbo** [comment]
@theathorn Jodi had someone at the Broad working on this. Did the diagram ever make it onto the portal? (moving ticket to you.)

**Comment by theathorn** [comment]
Superseded by https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-content/203
