### ISSUE TITLE
Branding colors - coordinating with Brand team

### ISSUE THREAD

**Issue by happyimadesignr** [DataBiosphere/data-portal#136]
Conversation with Suzan (Moth and Rust) and Jay (from the Brand Working Group)

**Comment by NoopDog** [comment]
![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/d26cfa51-3ade-48d7-aa2a-90d8d45c3248)

@frano-m our outcome from the call with Moth and Rust was to update the colors to the above.
Thanks!
