### ISSUE TITLE
Work with metadata team to get data for human image and homepage stats

### ISSUE THREAD

**Issue by happyimadesignr** [DataBiosphere/data-portal#138]
Doing it by hand right now has proven to be difficult and isn't very scalable. Do we want to think of a method to pull the data? @theathorn @NoopDog

**Comment by theathorn** [comment]
For summary stats see: https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/17

**Comment by theathorn** [comment]
See https://app.zenhub.com/workspace/o/databiosphere/azul/issues/113.

**Comment by theathorn** [comment]
Fixed by https://app.zenhub.com/workspace/o/databiosphere/azul/issues/47
