### ISSUE TITLE
Dropdowns in main nav to show secondary nav items. Follow the content outline.

### ISSUE THREAD

**Issue by happyimadesignr** [DataBiosphere/data-portal#139]
![Screen Shot 2018-06-26 at 4.28.42 PM.png](https://images.zenhubusercontent.com/5ab9846b4b5806bc2bcc80e2/beef7f4b-408b-46e3-bf02-1d32d73f25d9)

**Comment by frano-m** [comment]
@happyimadesignr I'm going to line up the secondary nav item text with the main nav text - which will mean that the box outline extends to the LHS of the main nav - let me know if you would prefer the outline of the box to line up with the main nav text (easy to reposition if this is your preference)...

@happyimadesignr take a look at how I done this - notice how if the user has a smaller screen and the header links are confined by limited space - if we did the drop down always left aligned, then `learn` and `build` links would have their secondary nav items off the screen... so my solution was to right align these two!  let me know if you want it any other way...

@happyimadesignr finally - last Q - do you want the hover state to stay active (black font colour) if you are looking in a non-active sub nav?

**Comment by happyimadesignr** [comment]
1. Let's reposition it to line up the edge of the box with the start of the main nav text.
2. I would align them left as much as possible and align right only when needed on small screens.
3. Yes, when you're in Analyze and you hover to Portals, let's keep Analyze in the active state.

Thanks Fran!

**Comment by happyimadesignr** [comment]
The current implementation needs more space between the secondary nav options. Can you also put a $white-off background color on hover.

![Screen Shot 2018-06-29 at 4.16.25 PM.png](https://images.zenhubusercontent.com/5ab9846b4b5806bc2bcc80e2/d6b0e35c-05e1-4613-821e-2cda2c9cf4c2)
