### ISSUE TITLE
Create Stub Doc for Help and Update Help Link to Point to It.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#150]

**Comment by theathorn** [comment]
Adrienne has a prototype for the Help Page: https://app.salesforceiq.com/r?target=5b36b78ec9e77c0079a8f775&t=AFwhZf21jfObzWiCFFuxNJw66P5KTOfBFr84j68RsrFvuli124zhvTN13ZDdRDBuYnarIV2VUjjsFw-bIIYPM5YVsh1TcoNgudFYG8UwgcAR_eCeA2Ox7-0YagfUzsU6sZcrViVZ6hUP
