### ISSUE TITLE
SynEcoSys

### ISSUE THREAD

**Issue by nicoleduan9716** [DataBiosphere/data-portal#1511]
Thank you for submitting a portal to the HCA DCP Methods Registry!

To expedite your portal's addition to https://data.humancellatlas.org/analyze,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your portal's detail page ([example](https://data.humancellatlas.org/analyze/portals/asap)).

Required:
- Tool title: SynEcoSys single-cell RNA sequencing database
- Contact name: SynEcoSys Team
- Contact email: sesinfo@singleronbio.com
- Who to attribute: B Liang, L Shi, WY Wang, JJ Chang, Y Lu, H Hou, GJ Wu, YC He, YH Fei, XG Zhang, JJ Wang, MM Wang, Y Zhang, J Ye, JN Liu, Y Guo, SS Chen, JC Duan, J Fan
- Portal URL: www.synecosys.cn
- Short description: SynEcoSys is a multifunctional platform for single-cell transcriptomic data analysis, visualization, and exploration. SynEcoSys curates both clinical and research orientated data to regard disease related cells and genes.

Optional:
- Long description: (will appear on detail page)
- Logo or screenshot: (attach to this GitHub issue.)
SynEcoSys is an online database application providing an extensive collection of single-cell sequencing data from published studies including real-world clinical samples. All provided datasets are processed with uniform standards of data analysis and cell type annotation to guarantee precision and inter-comparability. For disease-related datasets, any available clinical information associated with the single-cell data including descriptions from the text of publications are collected and organized as sample metadata, such as patient disease stages, disease subtypes, mutations carried, treatment methods, and responses to treatment. These features highlight SynEcoSys as the first-in-the-field single-cell sequencing database capable of clinical translations, supporting data mining for pharmaceuticals, therapeutics, and researches. 
![1](https://user-images.githubusercontent.com/105101011/170193464-8ed53246-559d-42be-aa3f-a04b2e893364.png)

SynEcoSys offers user-friendly data exploration platform for researchers with or without programming experience. CeleViz and CeleLens tools are embedded in SynEcoSys to offer elegant graphical graphical interfaces for visualizing dimensionality reduction, gene expression, cellular composition, differentially expressed genes analysis, inter-group comparisons, trajectory analysis, cell-cell interaction analysis, and automatic cell type annotation with in-house references. 
![2](https://user-images.githubusercontent.com/105101011/170194090-51d9afe5-6d68-408f-83bb-66edeaf1c2cb.png)

**Comment by theathorn** [comment]
Request approved.

**Comment by NoopDog** [comment]
Thx will implement.

**Comment by NoopDog** [comment]
@nicoleduan9716 @theathorn the SynEcoSys page is live here:
https://data.humancellatlas.org/analyze/portals/synecosys

Thank you for the portal submission!
Cheers,
D

**Comment by nicoleduan9716** [comment]
Awesome! Thank you so much!&nbsp;








 -----------------


&nbsp; 段嘉宸 生信与数据中心

Mob：+86-18341180301

Emai: ***@***.***

&nbsp; &nbsp; &nbsp;Web：www.singleronbio.com



 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Jun 22, 2022 01:11 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [DataBiosphere/data-portal] SynEcoSys (Issue #1511)

&nbsp;



 
@nicoleduan9716 @theathorn the SynEcoSys page is live here:
 https://data.humancellatlas.org/analyze/portals/synecosys
 
Thank you for the portal submission!
 Cheers,
 D
