### ISSUE TITLE
See why this list has an extra line break after the numbers.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#154]
![Screen Shot 2018-07-10 at 10.25.00 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/03bce299-0c8f-4127-bef4-dff0c74526aa)

**Comment by frano-m** [comment]
List items should not have a line-break in-between each item

For example - a list item in markdown should be written like this:

```
1. I am a list item
2. I am the next list item
3. I am the last list item
```

A list item should not look like this:

```
1. I am a list item

2. I am the next list item

3. I am the last list item
```
