### ISSUE TITLE
Modify Sitemap to support short URL to Pages with No Menu Header

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#156]
Contact and Help are implemented but have funny URLs because the sitemap was originally setup to handle sections with a 2nd and 3rd level menu. Contact and help don't have a 2nd level menu but we currently fake one to get it to fit into the sitemap so the url is:

https://dev.data.humancellatlas.org/contact/contact/contact-us

For example instead of just

https://dev.data.humancellatlas.org/contact

We need to modify the sitemap code to get this shorter url.

**Comment by theathorn** [comment]
@NoopDog @frano-m Can we shorten this:
https://staging.data.humancellatlas.org/privacy/privacy/privacy
to:
https://staging.data.humancellatlas.org/privacy
