### ISSUE TITLE
Update Privacy statement

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#1570]
Update the [DCP Privacy/GDPR statement](https://data.humancellatlas.org/privacy) according to the edits in the attached document.

[https://app.zenhub.com/files/124946282/d239b139-0d6d-4d36-80bf-d0d28caefb7c/download](https://app.zenhub.com/files/124946282/d239b139-0d6d-4d36-80bf-d0d28caefb7c/download)

For the contact email I suggest using data-help@humancellatlas.org, unless there is something more appropriate already in existence.

**Comment by theathorn** [comment]
[Revised Privacy notice](https://docs.google.com/document/d/142A__AlMb3yVpO17XIEYYuzKUlBGtGrw).

**Comment by NoopDog** [comment]
Hi, @trevor do you have this document as a Google Doc link? It is currently a docx file. Thanks, D

**Comment by theathorn** [comment]
The google doc is linked in my prior comment.

**Comment by trevor** [comment]
👋

**Comment by theathorn** [comment]
@MillenniumFalconMechanic Please add a semi-colon after the first occurrence of the word "function" in the last sentence of section 7: "If cookies are turned off the portal and browser will continue to function; however Google Analytics tracking will not function."

**Comment by theathorn** [comment]
OK to deploy to LungMAP `prod`.
