### ISSUE TITLE
Update HCA DCP GDPR and IPA privacy notices

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#1644]
[GDPR Privacy Notice for Human Cell Atlas Data Portal Public Website 7.12.22 4861-3196-5225 v.1](https://docs.google.com/document/d/1ud5XpqHvEh9dlCYHWxGSWcp5uomBK9-1).
[IPA Privacy Notice for Human Cell Atlas Data Portal Public Website 7.12.22 4860-9008-7721 v.1](https://docs.google.com/document/d/1YofBSF5mZrI_6AjriP4tEW1JBd3Q5A23).

**Comment by frano-m** [comment]
@theathorn would you mind please confirming the contact email for the GDPR privacy notice (currently is `contactdata-help@humancellatlas.org.y67uuuuuuuuuuuuuu6`) - thank you! I've assumed it should be `data-help@humancellatlas.org`.

**Comment by theathorn** [comment]
Yes, data-help@humancellatlas.org.
