### ISSUE TITLE
Where do we store licenses for products we've purchased to construct the portal?

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#168]
- Icons from the Noun Project
    - other icons
    - fonts
    - what else?

Suggestions include a "licenses" directory in the data-portal repo or consult with the Dev Ops team (Rhian Anthony) for their preference.

**Comment by theathorn** [comment]
@happyimadesignr please complete the list of licensed items in the Description and then re-assign this ticket to me or @kozbo.

**Comment by NoopDog** [comment]
HI @adriennes 

Is there some set of artifacts that we have that prove we have licsences to:

- Icons from the Noun Project
- other icons
- fonts
- images that were purchased

If you can attach them to this ticket I can add them to the repo.
Perhaps you can coordinate with @happyimadesignr to collect this info?

Cheers,
Dave

**Comment by happyimadesignr** [comment]
Hi @NoopDog @adriennes, this is on me, I can get these to you by the end of the week. Sorry for the delay.

**Comment by NoopDog** [comment]
Thanks @happyimadesignr

**Comment by NoopDog** [comment]
@theathorn  The license files have been added to the repo here:
https://github.com/HumanCellAtlas/data-portal/tree/develop/art-asset-licenses
