### ISSUE TITLE
Portal for addition to the HCA DCP Methods Registry: Bioconductor

### ISSUE THREAD

**Issue by mtmorgan** [DataBiosphere/data-portal#1682]
Thank you for submitting a portal to the HCA DCP Methods Registry!

To expedite your portal's addition to https://data.humancellatlas.org/analyze,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your portal's detail page ([example](https://data.humancellatlas.org/analyze/portals/asap)).

Required:
- Tool title: Bioconductor
- Contact name: Martin Morgan
- Contact email: mtmorgan.bioc@gmail.com
- Who to attribute: Bioconductor organization
- Portal URL: https://bioconductor.org
- Short description: Bioconductor provides more than 2100 R packages for the statistical analysis, comprehension, and visualization of high-throughput genomic data

Optional:
- Long description: [Bioconductor](https://bioconductor.org/) provides R packages for the statistical analysis, comprehension, and visualization of high-throughput genomic data; more than [250 packages](https://bioconductor.org/packages/release/BiocViews.html#___SingleCell) are tagged for use in single-cell analysis. Discover, visualize, and download data sets for further analysis using the [hca](https://bioconductor.org/packages/hca) and [cellxgenedp](https://bioconductor.org/packages/cellxgenedp) packages; details are outlined in package vignettes ([hca](https://bioconductor.org/packages/release/bioc/vignettes/hca/inst/doc/hca_vignette.html), [cellxgenedp](https://bioconductor.org/packages/release/bioc/vignettes/cellxgenedp/inst/doc/using_cellxgenedp.html)). Directly integrate Human Cell Atlas data into the Bioconductor ecosystem by following workflows for quality control, data integration, dimensionality reduction, clustering & visualization, cell annotation, and more as described in [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/OSCA/).
- Logo or screenshot: (attach to this GitHub issue.) 
![Screen Shot 2022-08-15 at 11 07 46 AM](https://user-images.githubusercontent.com/118552/184661921-8137f6e7-9db8-435d-b1c1-9eda5c6f6d27.png)

**Comment by NoopDog** [comment]
@mtmorgan @theathorn This is live here:

https://data.humancellatlas.org/analyze/portals/bioconductor

Martin, please feel free to submit a PR using the "Improve this page" link at the bottom of the page. With any updates. Thanks for submitting.

Cheers,
Dave Rogers

**Comment by mtmorgan** [comment]
Thanks Dave et al.!
