### ISSUE TITLE
GDPR statement for the Data Portal

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#169]
From @lauraclarke:

I thought you would find it useful to see what the GDPR statements we 
have put out about the different ingest systems in case you need 
inspiration for the Data portal one.

These are our four.

1) Human Cell Atlas Register of Interest
http://www.ebi.ac.uk/data-protection/privacy-notice/human-cell-atlas-register-of-interest

2) Human Cell Atlas Ingest Access Service - Terms and Conditions form.
http://www.ebi.ac.uk/data-protection/privacy-notice/human-cell-atlas-ingest-submission

3) Human Cell Atlas Zendesk and Email Services
http://www.ebi.ac.uk/data-protection/privacy-notice/human-cell-atlas-zendesk

4) Human Cell Atlas Ingest Submission Service - API
http://www.ebi.ac.uk/data-protection/privacy-notice/human-cell-atlas-ingest-access-service

Getting started on this quickly is a good idea as you will need to seek 
approval for the text from the 4 institutions legal counsel and that can 
take a little time. For contact there you need

Shawn Liu sliu@chanzuckerberg.com  CZI
Crystal Mao crystalm@broadinstitute.org Broad Institute
Rachel Devlahovich Sievert rsievert@ucsc.edu UCSC
Dominik Reske reske@embl.de EMBL

Do include the project leads from all four centres to so we know what is 
happening.

**Comment by theathorn** [comment]
Laura wrote:
Any service where we collect information like name, email and IP from users needs a GDPR statement. The data portal definitely needs one. This is how the biosamples database links to it on their about page https://www.ebi.ac.uk/biosamples/about Ensembl puts it in their footer which might be easier for us http://www.ensembl.org/index.html

@NoopDog what's your input on this?

**Comment by NoopDog** [comment]
We can make a nice looking opt in on the bottom of the page just above the footer that goes away once you accept. Some questions:

1. Do we need to somehow save the fact that the user accepted or is this just a convenience for them to dismiss the privacy notice and get some of their screen back?

1. Do we have the text for the notice bar, and the privacy statements?

Cheers,
D

**Comment by theathorn** [comment]
Let's review this: https://docs.google.com/document/d/1ZDv_i7eAv6_ACRHlH7lQ8_-N2P_3G_VOMbNns1-M95E/edit

..which is approved for zendesk & email services (which we use via the Contact and Help links.

Should we just have one GDPR statement for the overall Portal? Do we need a separate one for the Browser?

**Comment by lauraclarke** [comment]
An important thing to note that your GDPR statements will need to be reviewed and actively approved by legal counsel from all four institutes and this will need to happen for any edits.

The reason to have two different statements will be if the two services collect different types of personally identifiable data or that is likely in the near term because of the overhead of updating the policies is high so tying them together carries a risk. This is why we have different statements for the different parts of ingest

Note the Consumer API might also need one, not sure who that should be flagged to @kozbo ?

**Comment by theathorn** [comment]
We collect: IP address, email address, name(from Auth0), avatar, google access/refresh token, statistics on pages visited.

**Comment by lauraclarke** [comment]
Presumably you don't collect email address or name and avatar by default as people don't have to login to use the service?

**Comment by theathorn** [comment]
@lauraclarke We don't collect email addresses at start of Pilot but we will shortly afterwards when we support Collections or hand-off to Firecloud, etc.
So I think we want the "larger" GDPR statement to avoid going back to the lawyers a second time.

**Comment by lauraclarke** [comment]
@theathorn it is worth noting that you probably can't have the same GDPR statement for the cookie based tracking you will do to anonymous users and the users who sign in. You will track different things about these two classes of users so they shouldn't use the same statement.

**Comment by theathorn** [comment]
@NoopDog The approved GDPR statement for the Data Portal is here:
https://docs.google.com/document/d/1fnQINoch_baf-hseCOKXW4OWcM-TadMCwfpLWwRRhJ4/edit#heading=h.b78bd7xh8g1a
Let's work out the best way to present it to the user.
