### ISSUE TITLE
Broken links - Metadata section

### ISSUE THREAD

**Issue by idazucchi** [DataBiosphere/data-portal#1837]
Hi,

I'm not sure this is the right repo for this ticket, please feel free to move it!

I've found a couple of broken links and it would be nice to get them fixed.
1. [metadata structure](https://data.humancellatlas.org/metadata/structure) - _improve the documentation_
2. [metadata design](https://data.humancellatlas.org/metadata/rationale) - _improve the documentation_ and _HCA Metadata Schema Style and Formatting Guide_. I think the last one could be linked to [this document](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/schema_style_guide.md) in the metadata repo

**Comment by NoopDog** [comment]
Obsolete Thx!
