### ISSUE TITLE
Update "Updates" Page for DCP 21 

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#1845]
#### New projects (5)
1. [COVID-19 tissue atlases reveal SARS-CoV-2 pathology and cellular targets.](https://data.humancellatlas.org/explore/projects/61515820-5bb8-45d0-8d12-f0850222ecf0)
1. [Differential dynamics of response at single cell resolution following CAR-T therapy in refractory B-cell lymphoma](https://data.humancellatlas.org/explore/projects/c0d82ef2-1504-4ef0-9e5e-d8a13e45fdec)
1. [Genome-Wide DNA Hypermethylation in the Wound-Edge of Chronic Wound Patients Opposes Closure by Impairing Epithelial to Mesenchymal Transition](https://data.humancellatlas.org/explore/projects/34ec845b-cd7a-4c43-99e4-d2932d5d85bb)
1. [Intratumoral heterogeneity in recurrent pediatric pilocytic astrocytomas](https://data.humancellatlas.org/explore/projects/575c0ad9-c78e-469b-9fdf-9a68dd881137)
1. [Single-cell analysis of childhood leukemia reveals a link between developmental states and ribosomal protein expression as a source of intra-individual heterogeneity](https://data.humancellatlas.org/explore/projects/1fa8b11f-56fa-45a6-a777-6af70e17a6b3)

#### Updated Projects (2)
1. [Expansion of Fcγ Receptor IIIa-Positive Macrophages, Ficolin 1-Positive Monocyte-Derived Dendritic Cells, and Plasmacytoid Dendritic Cells Associated With Severe Skin Disease in Systemic Sclerosis](https://data.humancellatlas.org/explore/projects/7f351a4c-d24c-4fcd-9040-f79071b097d0)

1. [A single-cell and single-nucleus RNA-seq toolbox for fresh and frozen human tumors.](https://data.humancellatlas.org/explore/projects/a62dae2e-cd69-4d5c-b5f8-4f7e8abdbafa)

**Comment by ekiernan** [comment]
PR is here: https://github.com/DataBiosphere/data-portal/pull/1849/files
