### ISSUE TITLE
Remove the “Processed by the Data Processing Pipelines” from "Contribute" section

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#1967]
Remove the "processed by our standard data processing pipelines" paragraph from the [Data Processing and Results](https://data.humancellatlas.org/contribute/contributing-data-processing-results) page.

**Comment by NoopDog** [comment]
Completed closing:
https://data.humancellatlas.org/contribute/contributing-data-processing-results
@theathorn
