### ISSUE TITLE
Polly by Elucidata

### ISSUE THREAD

**Issue by Aqsa-el** [DataBiosphere/data-portal#2096]
Thank you for submitting a portal to the HCA DCP Methods Registry!

To expedite your portal's addition to https://data.humancellatlas.org/analyze,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your portal's detail page ([example](https://data.humancellatlas.org/analyze/portals/asap)).

Required:
- Tool title: Polly by Elucidata
- Contact name: Team El
- Contact email: team-elucidata@elucidata.io
- Who to attribute: Elucidata
- Portal URL: https://polly.elucidata.io/
- Short description: (<= 200 characters, will appear on list page)
Polly is a data-ops platform that provides access to 50,000 curated Bulk & Single Cell RNA-Seq Data, facilitating rapid detection of drug targets and biomarkers across diseases.

Optional:
- Long description: (will appear on detail page)
[Polly](https://www.elucidata.io/platform/features) is a biomedical data platform for life sciences R&D, primarily delivering bulk RNA-seq and single-cell data, along with 24 other data types. It delivers **155 TB of FAIR and ML-ready biomedical data from ~30 different (primarily public) sources** to customers. 

Polly takes care of data ingestion, transformation, and storage. Therefore, researchers can focus on insight derivation via **data analysis, visualization instead of data wrangling and engineering**. It is easy to incorporate Polly into your existing data infrastructure because we offer integrations to your existing data storage units as well as **analysis/visualization, and computational tools**. 

Polly creates a unique, centralized ecosystem that enables a diverse team of biologists, bioinformaticians, and scientific leaders to share and collaborate on workspaces, data, and insights. It has enabled the detection of multiple validated drug targets across immunology, oncology, and metabolic disorders using ML-ready and a scalable data infrastructure for downstream analysis provided by Polly.

- Logo or screenshot: (attach to this GitHub issue.)
![Logo_High](https://user-images.githubusercontent.com/128775167/230396076-61f174c9-b502-4fb9-82c3-595810fd677d.png)

**Comment by NoopDog** [comment]
Hi @Aqsa-el, thank you for submitting the tool.  We will start our review and let you know if we have any questions. 
Cheers, Dave Rogers

**Comment by Aqsa-el** [comment]
Thanks a ton Dave. Will await your response.

**Comment by Aqsa-el** [comment]
Hey Dave, I was wondering if there is an update on this yet?

**Comment by Aqsa-el** [comment]
> Hi @Aqsa-el, thank you for submitting the tool. We will start our review and let you know if we have any questions. Cheers, Dave Rogers

Hi Dave, is there an update on this?

**Comment by Aqsa-el** [comment]
Hi David, can you tell me if the request has been approved? I can't see it
on the tools registry page.

**Comment by NoopDog** [comment]
HI @Aqsa-el this is now [live](https://data.humancellatlas.org/analyze/portals/polly-by-elucidata). Thanks again for the submission and apologies this got lost in the shuffle for a bit. Cheers, D

**Comment by Aqsa-el** [comment]
Awesome, thanks for the update!
