### ISSUE TITLE
Create Data Portal Content Repository

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#21]
Please create a content repo for the data portal maybe `data-portal-content` that we can use to store the markdown content for the site.

Initially please add me noopdog and the rest of the Clever Canary team team fran and mim.
Once we get this going we can add others. 

Thanks!

**Comment by parthshahva** [comment]
https://github.com/HumanCellAtlas/data-portal-content created. Thanks @ttung
