### ISSUE TITLE
Set up Google analytics for the Portal

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-portal#210]
[Link to metrics proposal](https://docs.google.com/document/d/1gqAwyv3k2ad3y7YH9iVMDPYxRskz6MJiueGikz1hCoI/edit?disco=AAAABzg0RnA&ts=5b632563)

**Comment by theathorn** [comment]
From PM meeting:
Idea for implementation: UCSC will own a google analytics project (short term). This will be transfer to a data operations team long-term. There may be a access list defined by the PM++.

**Comment by theathorn** [comment]
What does it entail to have a UCSC email address as the owner of a google analytics project? Do we use someone's existing address (e.g. theathor@ucsc.edu) or define a special purpose address (e.g. hca-admin@ucsc.edu)?

**Comment by theathorn** [comment]
Awaiting GDPR approval before enabling in Prod env.

**Comment by NoopDog** [comment]
This is enabled in prod @theathorn
