### ISSUE TITLE
Update updates page for catalog hca26

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#2106]
New projects (3):
1. [A Partial Picture of the Single-Cell Transcriptomics of Human IgA Nephropathy](https://data.humancellatlas.org/explore/projects/c5b475f2-76b3-4a8e-8465-f3b69828fec3)
1. [Mucosal Profiling of Pediatric-Onset Colitis and IBD Reveals Common Pathogenics and Therapeutic Pathways](https://data.humancellatlas.org/explore/projects/f3825dfe-990a-431f-b971-9c26d39840db)
1. [Single-Cell Atlas of Lineage States, Tumor Microenvironment, and Subtype-Specific Expression Programs in Gastric Cancer](https://data.humancellatlas.org/explore/projects/c281ab63-7b7d-4bdf-b761-9b1baaa18f82)

Updated projects (2)
1. [Severe COVID-19 Is Marked by a Dysregulated Myeloid Cell Compartment](https://data.humancellatlas.org/explore/projects/cd9d6360-ce38-4321-97df-f13c79e3cb84)
1. [Vento-tormo: Single cell profiling of COVID-19 patients: an international data resource from multiple tissues](https://data.humancellatlas.org/explore/projects/2d4d89f2-ebeb-467c-ae60-a3efc5e8d4ba)

**Comment by kayleemathews** [comment]
PR for updates is here: https://github.com/DataBiosphere/data-portal/pull/2111

**Comment by NoopDog** [comment]
Complete
