### ISSUE TITLE
CellKb

### ISSUE THREAD

**Issue by combinatics** [DataBiosphere/data-portal#2126]
Thank you for submitting a portal to the HCA DCP Methods Registry!

To expedite your portal's addition to https://data.humancellatlas.org/analyze,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your portal's detail page ([example](https://data.humancellatlas.org/analyze/portals/asap)).

Required:
- Tool title: CellKb
- Contact name: CellKb Support
- Contact email: cellkb@combinatics.com
- Who to attribute: Combinatics
- Portal URL: https://www.cellkb.com
- Short description: CellKb is a knowledgebase of cell type marker gene sets manually collected and curated from scientific literature. All cell types are extensively annotated with information about tissue, disease and experimental conditions, and integrated with protein-protein interaction networks. CellKb allows users to rapidly search through published cell type signatures to annotate single-cell and spatial RNA-seq data. It can also be used to compare cell type marker gene sets across tissues, diseases and species for biomarker discovery.

Optional:
- Long description: (will appear on detail page)

- Logo or screenshot: (attach to this GitHub issue.)
![CellKb_banner](https://github.com/DataBiosphere/data-portal/assets/64998079/31da18e6-a12e-4431-bf1f-635506b4fabf)

**Comment by mrtopsyt** [comment]
Hi @combinatics, looks like this might have fallen through the cracks on our end but we're adding it now! Just wanted to check if there were any changes you wanted for the "Short description" section, since it appears CellKb Immune has been discontinued since this was submitted? Thanks so much!

**Comment by combinatics** [comment]
@jpaten , I have updated the "Short description" section to remove a reference to CellKb Immune. Thank you!

**Comment by mrtopsyt** [comment]
Great thank you so much! We'll get it added to the site shortly

**Comment by NoopDog** [comment]
Apologies, the Analysis portal selection of the site has been retired and may be back in a different form at a later date. Closing this issue for now.
