### ISSUE TITLE
Create Privacy notice mockup

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#216]
Create a notice at foot of browser which redirects new user to GDPR privacy statement.

**Comment by theathorn** [comment]
See #169.

**Comment by frano-m** [comment]
For review:
https://chanzuckerberg.invisionapp.com/d/main#/console/14304893/316191625/preview
https://chanzuckerberg.invisionapp.com/d/main#/console/14304893/316191624/preview
