### ISSUE TITLE
[Atlas Pages] Complete Lung V1 Atlas pages

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#2183]
- [x] Remove the core atlas from the  "Component Atlases" section
- [x] Update Component Atlases section as per new mocks with link to cellxgene and download
- [x] Add Analysis Portals Section with link to cellxgene collection https://cellxgene.cziscience.com/collections/8a072d7c-99cb-4112-83e3-6061165dd491
- [x] Collect remaining "Source Datasets"
- [x] Add remaining "Source Datasets"

TODO Dave
- [ ] new name for collections link
- [ ] modal for h5ad / rds

**Comment by frano-m** [comment]
See https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/HCA-Data-Explorer?type=design&node-id=5198-19411&mode=design&t=M7KtZAwjwwEuM5pv-4

**Comment by NoopDog** [comment]
Complete
