### ISSUE TITLE
Matilda

### ISSUE THREAD

**Issue by liuchunlei0430** [DataBiosphere/data-portal#2199]
Thank you for submitting a method package to the HCA DCP Analysis Tools Registry!

To expedite your package's addition to https://data.humancellatlas.org/analyze/methods,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your package's detail page ([example](https://data.humancellatlas.org/analyze/methods/stream)).

[Required](https://data.humancellatlas.org/contribute/analysis-tools-registry#package-submission-field-details):
- Tool title: Matilda
- Contact name: PYangLab
- Contact email: cliu@cmri.org.au
- Who to attribute:  PYangLab
- Method-ready Docker image URL: https://github.com/PYangLab/Matilda/tree/main/img/main.jpg
- Code repository URL: https://github.com/PYangLab/Matilda
- Affirm code is free and open source with license available in code repository: [x] (fill in as [x] to affirm)
- Language: English
- Upstream registry URL: https://github.com/PYangLab/Matilda/tree/main/img/main.jpg
- Test data location: https://github.com/PYangLab/Matilda/tree/main/data/TEAseq 
- Basic command line usage: 
```
# training the matilda model
python main_matilda_train.py --rna [trainRNA] --adt [trainADT] --atac [trainATAC] --cty [traincty] #[training dataset]
# python main_matilda_rna_train.py --rna [trainRNA] --cty [traincty]
# Example run
python main_matilda_train.py --rna ../data/TEAseq/train_rna.h5 --adt ../data/TEAseq/train_adt.h5 --atac ../data/TEAseq/train_atac.h5 --cty ../data/TEAseq/train_cty.csv #Training TEAseq
#python main_matilda_train.py --rna ../data/TEAseq/train_rna.h5 --adt ../data/TEAseq/train_adt.h5  --cty ../data/TEAseq/train_cty.csv #Training CITEseq
#python main_matilda_train.py --rna ../data/TEAseq/train_rna.h5 --atac ../data/TEAseq/train_atac.h5 --cty ../data/TEAseq/train_cty.csv #Training RNA+ATAC
# python main_matilda_rna_train.py --rna ../data/TEAseq/train_rna.h5 --cty ../data/TEAseq/train_cty.csv # for scRNA-seq
```

- Command to validate installation: 
```
# training the matilda model
python main_matilda_train.py --rna [trainRNA] --adt [trainADT] --atac [trainATAC] --cty [traincty] #[training dataset]
# python main_matilda_rna_train.py --rna [trainRNA] --cty [traincty]
# Example run
python main_matilda_train.py --rna ../data/TEAseq/train_rna.h5 --adt ../data/TEAseq/train_adt.h5 --atac ../data/TEAseq/train_atac.h5 --cty ../data/TEAseq/train_cty.csv #Training TEAseq
#python main_matilda_train.py --rna ../data/TEAseq/train_rna.h5 --adt ../data/TEAseq/train_adt.h5  --cty ../data/TEAseq/train_cty.csv #Training CITEseq
#python main_matilda_train.py --rna ../data/TEAseq/train_rna.h5 --atac ../data/TEAseq/train_atac.h5 --cty ../data/TEAseq/train_cty.csv #Training RNA+ATAC
# python main_matilda_rna_train.py --rna ../data/TEAseq/train_rna.h5 --cty ../data/TEAseq/train_cty.csv # for scRNA-seq
```
- Short description: Matilda is a multi-task framework for learning from single-cell multimodal omics data. Matilda leverages the information from the multi-modality of such data and trains a neural network model to simultaneously learn multiple tasks including data simulation, dimension reduction, visualization, classification, and feature selection.

[Optional](https://data.humancellatlas.org/contribute/analysis-tools-registry#optional-fields-for-methods-and-visualizations):
- Long description: (will appear on detail page)
- Build badge URL: (e.g. https://travis-ci.org/kstreet13/slingshot.svg?branch=master)
- Coverage badge URL: (e.g. https://img.shields.io/codecov/c/github/kstreet13/slingshot/master.svg)
- Logo: (attach to this GitHub issue)
- Screenshot: (attach to this GitHub issue)
- Implementation of this tool in an active portal: URL
- Benchmark dataset: URL

**Comment by NoopDog** [comment]
@liuchunlei0430 this is live here https://data.humancellatlas.org/analyze/methods/matilda
Thanks for submitting the package!
Cheers,
D
