### ISSUE TITLE
Cepo

### ISSUE THREAD

**Issue by HaniJieunKim** [DataBiosphere/data-portal#2202]
Thank you for submitting a method package to the HCA DCP Analysis Tools Registry!

To expedite your package's addition to https://data.humancellatlas.org/analyze/methods,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your package's detail page ([example](https://data.humancellatlas.org/analyze/methods/stream)).

[Required](https://data.humancellatlas.org/contribute/analysis-tools-registry#package-submission-field-details):
- Tool title: Cepo
- Contact name: Hani Jieun Kim
- Contact email: hani.kim127@gmail.com
- Who to attribute: Hani Jieun Kim
- Method-ready Docker image URL:
- Code repository URL: https://github.com/PYangLab/Cepo
- Affirm code is free and open source with license available in code repository: [x]
- Language: R
- Upstream registry URL: (URL or placeholder for upstream registry submission)
- Test data location: https://github.com/PYangLab/Cepo/tree/main/data
- Basic command line usage: Extensive command line usage in R or RStudio provided at https://pyanglab.github.io/Cepo/
- Command to validate installation: 
- Short description: Defining the identity of a cell is fundamental to understand the heterogeneity of cells to various environmental signals and perturbations. We present Cepo, a new method to explore cell identities from single-cell RNA-sequencing data using differential stability as a new metric to define cell identity genes. Cepo computes cell-type specific gene statistics pertaining to differential stable gene expression.

[Optional](https://data.humancellatlas.org/contribute/analysis-tools-registry#optional-fields-for-methods-and-visualizations):
- Long description: (will appear on detail page)
- Build badge URL: (e.g. https://travis-ci.org/kstreet13/slingshot.svg?branch=master)
- Coverage badge URL: (e.g. https://img.shields.io/codecov/c/github/kstreet13/slingshot/master.svg)
- Logo: (attach to this GitHub issue)
- Screenshot: (attach to this GitHub issue)
- Implementation of this tool in an active portal: URL
- Benchmark dataset: URL

**Comment by frano-m** [comment]
Hi @HaniJieunKim, there seems to be a problem with the `Build badge URL`: https://travis-ci.org/kstreet13/slingshot.svg?branch=master. Is there some other link we could use instead? Thanks
