### ISSUE TITLE
Make dcp32 the default catalog for HCA

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/data-portal#2214]
The approvals can be found in [this Slack thread](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1697518396836619). 

This ticket blocks https://github.com/DataBiosphere/azul/issues/5642

**Comment by bvizzier-ucsc** [comment]
The Azul team is removing the accidentally included dataset.  Please see  https://github.com/DataBiosphere/azul/issues/5642

**Comment by NoopDog** [comment]
@bvizzier-ucsc informed me the bad dataset has been removed. We will go ahead and deploy this, hopefully this evening.

**Comment by NoopDog** [comment]
Complete
