### ISSUE TITLE
Update Atlas Download to latest CELLxGENE UX, add HCA Data

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#2323]
Also, add

<img width="417" alt="image" src="https://github.com/DataBiosphere/data-portal/assets/3239697/4036ed2a-9801-42c4-82af-7f8f58a7d7d3">

Do we need a design from K? Maybe just stretch this across the bottom? I can ask him for a design for this tonight.

Once we have this running, I need a screenshot to send to CZI for approval before we merge it.

**Comment by frano-m** [comment]
Yes please, let me have a design and also text and location of the box @NoopDog.
