### ISSUE TITLE
Support mashup badge in Analyze section

### ISSUE THREAD

**Issue by eweitz** [DataBiosphere/data-portal#233]
Implement support for "mashup" badges in package listing entries for [visualization components](https://dev.data.humancellatlas.org/analyze/visualization-components/visualization-components/).  Such badges would link to a mashup repo, e.g. https://github.com/eweitz/morpheus.js-react.

This would be a custom badge.  The work here would include creating a badge image with font and a mild skeuomorphic design like the existing badges for "build" and "coverage".  The "mashup" badge would differ from the other badge types in that it would only exist or not.  It would not have multiple states beyond simply existing like a passing/failing string or an integer representing percent of code covered by tests.

The badge image would be served as a static asset from the same server as other Data Portal static content.

See more at:
https://docs.google.com/document/d/1ANt1KB-EwmGoyHa94gP8J5vT0rr_bkhCVGJ13ZDj4i4/edit

**Comment by eweitz** [comment]
This feature was originally a stretch goal for #178.  I split it into a separate issue per @NoopDog's request.

**Comment by eweitz** [comment]
@vickylihorst, @TimothyTickle, let's discuss how this "mashup" badge would relate to the Detail page.  There's a fair amount of overlap between what a repo like https://github.com/eweitz/morpheus.js-react contains and what Detail pages would contain.

**Comment by frano-m** [comment]
Mashup badge located: `/analyze/_images/mashup.svg`

Markdown: ![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/09603fcc-bf88-477c-b8be-f8e8af8bd567)

![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/30fdf376-7e13-4709-98b8-2009294df298)

**Comment by NoopDog** [comment]
@eweitz let us know if this is what you are looking for above. One question. Are you looking to let other projects add the tab to their own repo's or are you just wanting to tag resources locally on the data portal?

**Comment by eweitz** [comment]
Nice, @frano-m and @NoopDog!  That's generally what is needed.  This badge would just be for tagging resources locally in the data portal.

**Comment by theathorn** [comment]
@eweitz Can we close this ticket then?

**Comment by eweitz** [comment]
@theathorn, yes.  I just added the mashup badge to Morpheus in https://dev.data.humancellatlas.org/analyze/visualization-components/visualization-components/ and see it working as expected.  Thanks all!
