### ISSUE TITLE
[Atlas Pages] Add Retina 1.0 atlas

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#2359]
CELLxGENE Collection
https://cellxgene.cziscience.com/collections/4c6eaf5c-6d57-4c76-b1e9-60df8c655f1e

Source Datasets
https://docs.google.com/spreadsheets/d/1DQn5Ae9_4nrek_tj6dreSPvf8BjY1cbP/edit#gid=1657680599

Updated Eye Network and Atlas Text
https://docs.google.com/document/d/1HjwZvK4evlo-fiJy97kdkOtIV0P3b9INpSRTNcSOC84/edit

**Comment by frano-m** [comment]
https://cellxgene.cziscience.com/collections/4c6eaf5c-6d57-4c76-b1e9-60df8c655f1e

**Comment by NoopDog** [comment]
@frano-m this source dataset is now in the HCA Data repository https://explore.data.humancellatlas.org/projects/aebc99a3-3151-482a-9709-da6802617763. Please replace the publication only view in the retina source datasets list with this link. 
Thanks!

**Comment by NoopDog** [comment]
Complete!
