### ISSUE TITLE
[HCA Portal] Validate pageview events are accessible on the GA4 Query Explorer for dev and prod 

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-portal#2436]
#### Need
HCA Portal currently has no custom events but requires tracking of pageviews.

#### Definition of Done
Confirm pageview events are visible in the query explorer for `data.humancellatlas.org - GA4` and `data.humancellatlas.dev.clevercanary.com - GA4`:

- [x] data.humancellatlas.org - GA4
- [x] data.humancellatlas.dev.clevercanary.com - GA4

**Comment by mrtopsyt** [comment]
Hi @MillenniumFalconMechanic! Here's a PR for a README:

https://github.com/DataBiosphere/data-portal/pull/2442

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic, marking this as blocked right now due to the removal of metadata search. Let me know what you want the next steps to be here!

**Comment by mrtopsyt** [comment]
Hi @MillenniumFalconMechanic! It appears to be working - see the following screenshots for example responses from Query Explorer:

Prod
<img width="508" alt="Screenshot 2024-10-03 at 2 42 38 PM" src="https://github.com/user-attachments/assets/5e580cce-175d-4ba0-ab3b-343bfa87fab1">

Staging
<img width="533" alt="Screenshot 2024-10-03 at 2 43 30 PM" src="https://github.com/user-attachments/assets/12732f32-83be-4cd6-802c-24f059946c81">

**Comment by MillenniumFalconMechanic** [comment]
LGTM, thanks @jpaten!
