### ISSUE TITLE
[HCA Portal] Update GTM outbound link configuration

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-portal#2468]
#### Need
Outbound links should track the source URL and capture the fragment if any.

#### Definition of Done
Additional outbound link information is accessible in the query manager for prod and staging:
- [x] data.humancellatlas.org - GA4
- [x] data.humancellatlas.dev.clevercanary.com - GA4

**Comment by mrtopsyt** [comment]
Working on prod but not staging, will check staging again tomorrow

<img width="505" alt="Screenshot 2024-10-14 at 4 33 20 PM" src="https://github.com/user-attachments/assets/f88b38da-3285-44fd-b9fe-5209d183ef39">

**Comment by mrtopsyt** [comment]
And now working on staging too. @MillenniumFalconMechanic should be good to go!
![Image](https://github.com/user-attachments/assets/d48b871c-52ae-43e1-9fbe-fed973732da2)

**Comment by MillenniumFalconMechanic** [comment]
Thanks Jonah!
