### ISSUE TITLE
Track clicks on "Explore Data" CTA

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-portal#2469]
#### Need
We need to add tracking of the primary CTA button on the homepage to monitor user interactions and optimize conversions. This tracking will allow us to analyze the conversion funnel more accurately, ensuring that the CTA is performing as expected.

#### Approach
* Add a `button-explore-data` ID to the "Explore Data" button.
* Use GTM's built-in click variables to enable click tracking.
* Create trigger that fires on "Click - All Elements" / "Some Clicks" to target only the "Explore Data" button.

#### Definition of Done
Clicks on "Explore Data" are accessible in the query explorer for both prod and staging:
- [x] data.humancellatlas.org - GA4
- [x] data.humancellatlas.dev.clevercanary.com - GA4

**Comment by mrtopsyt** [comment]
Reopening since GTM-side work isn't done yet

**Comment by mrtopsyt** [comment]
Working on prod and staging @MillenniumFalconMechanic 

Prod:
![Image](https://github.com/user-attachments/assets/f9791787-3030-4cb4-8605-ab1f4460d34f)

Staging:
![Image](https://github.com/user-attachments/assets/cdf8e721-44ec-4171-9a63-930c0cc4299a)

**Comment by MillenniumFalconMechanic** [comment]
Thanks Jonah!
