### ISSUE TITLE
Add more information about manifest to download confirmation pop-up

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-portal#258]
In download flow, after downloading manifest, users see a confirmation pop-up.  We should add a sentence here saying clarifying what the file manifest is.  
@jodihir  to suggest text

**Comment by jodihir** [comment]
Does this sentence work?:

The manifest is a tab-delimited file containing ID and version information about the data bundles and associated files that you requested.

**Comment by theathorn** [comment]
This needs to be in the data-browser repo...

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/265.
