### ISSUE TITLE
Modify Travis scripts to build and deploy the updated site for DEV

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#26]
So this is using  gatsby.js as a site generator for the code in  `develop` branch.

This needs node 10 to  install and run
once the npm (dev dependancies) are installed then its..

```gatsby build```

to build the site that will end up in the `public` folder.

public then needs to be copied to the S3 bucket and cache refreshed etc.

Right now and will then end up on https://dev.data.humancellatlas.org/

This currently would read only from local markdown, but we can then set up some triggers to get this  bit more elaborate and pull form a different repo for the markdown.

Lets discuss when you have a moment.

**Comment by NoopDog** [comment]
I have just pushed to develop so while the file will look ugly.  If you can get travis to:
@parthshahva 
                       
1. install node 10
1. npm install (need to install the dev dependancies)
1. gatsby build

then you should be able to deploy the `public` folder and have things basically work.

Let me know if you have any questions.

Cheers,
D

**Comment by parthshahva** [comment]
done
