### ISSUE TITLE
Make Metadata Dictionary Searchable

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-portal#260]
# Why
As a user I would like to be able to search for a specific metadata term in the dictionary to quickly locate the definition
As a user I would like to be able to search for a fully qualified metadata term in the dictionary to quickly locate the definition

From @hewgreen 
Many users don't care about the model and only see metadata as key value pairs. Therefore, I want to be able to use free text search to find similar attributes or specific programatic name e.g.
library_preparation_protocol.strand to find the attribute I need.

The info I needed was actually there Should be one of: "first", "second", "unstranded" or "not provided". Perfect.

But I would like to be able to click a link through to the metadata schema too. This would be mainly useful when the enums get long or for ontology fields where looking at the detail is useful.

Even more amazing would be some usage stats on these too. How many projects have used that attribute? This would allow me to find some examples from actual projects so I know how to use it. (I'm asking too much now I know)

Motivation:
Beta users had a hard time finding documentation on the metadata terms, and when they did find it they had a hard time finding the right section for their term.  This will be exacerbated by the fact that we will now be using fully qualified terms in the spreadsheet and matrix file outputs. We need will include a reference to the metadata dictionary in the Matrix output readme file, so next we need a way of finding content once there.

# Definition of Done
 - [ ] Provide a search box that can locate a metadata term in the dictionary from a single term
 - [ ] Provide a search box (same one) that can locate a metadata term in the dictionary from a fully qualified term

**Comment by kozbo** [comment]
@hannes-ucsc can help with context on this

**Comment by hannes-ucsc** [comment]
Users should be able to take a property reference (fully qualified or unqualified) like `donor_organism.biomaterial_core.biomaterial_id` or `biomaterial_id` from the header row of a manifest or metadata TSV and paste it into a text search field. The actual metadata property names (not just the display names) should also be included in the actual documentation.
