### ISSUE TITLE
Update dev dependencies to latest

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#2600]
#### Need
We have quite a few dev dependencies that have dependabot alerts that they have later versions and many of these versions are major version bumps that might require changes in the various configuration files.

#### Approach

Bump the versions to the latest where possible and modify the configuration files accordingly to keep the functionality consistent.

- Work with the team to resolve any new eslint errors.
- Review any prettier formatting changes to see if we want to configure them away (if possible) or take them.
- Update the build script command and GitHub actions as required.
- Test that the app builds and functions okay after the build.

AnVIL portal recently had its dev dependencies updated so we can use that as a guide.
https://github.com/anvilproject/anvil-portal/pull/3428
https://github.com/anvilproject/anvil-portal/pull/3428/commits

**Comment by mrtopsyt** [comment]
Dependabot alerts:

- [x] #2599 
- [x] #2590 
- [x] #2589
- [x] #2587 
- [x] #2583 
- [x] #2582 
- [x] #2576 
- [x] #2574 
- [x] #2562 
- [x] #2561 
- [x] #2560 
- [x] #2558 
- [x] #2539 
- [x] #2538 
- [x] #2532 
- [ ] #2529 
- [x] #2528
- [x] #2523 
- [ ] #2517 
- [x] #2515 
- [x] #2512 
- [x] #2511
- [x] #2508 
- [x] #2506
