### ISSUE TITLE
Create Data-Portal production environment

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#279]

**Comment by theathorn** [comment]
@kozbo would like this available the week of Nov. 12th (needed for Beta startup activities).
Prefix should be "prod" (not "pre-prod") and point to the production instance of DSS.

**Comment by NoopDog** [comment]
@theathorn  I have updated the dns to be prod. (instead of pre-prod).

I have also updated the portal and browser config to use the prod Azul and Matrix service endpoints.  Such as:

https://service.explore.data.humancellatlas.org/repository/summary

However currently the Azul prod is returning 403 for the project and summary endpoints. 
@hannes-ucsc ^^

Once that is corrected and we are indexed we should be good.
