### ISSUE TITLE
Update text alignment for better visual appeal

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-portal#280]
Currently, all the text in the Data Portal is "left aligned" (see below). I suggest to "justify" for the longer text entries for better visual balance and appeal. 

![screenshot 2018-10-29 at 15 34 42](https://user-images.githubusercontent.com/38244059/47661344-c6177600-db90-11e8-93ee-ce8b2d010e41.png)

**Comment by NoopDog** [comment]
HI @zperova left aligned is the way to go here. Center justifying will introduce large gaps in the text body making the site more difficult to read.

Closing this one, but please let us know if you see any other way to make the site more readable.
