### ISSUE TITLE
Display dismissable banner warning user of non-Production environment

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#288]
For "dev", "integration" and "staging" we should have a popup banner on the Data Portal home page warning the user "This is a test environment and periodically may be unavailable".
This should *not* be present in the Production environment.
The user shoudl be able to dismiss the warning so it's doesn't appear during future usage.

**Comment by NoopDog** [comment]
@theathorn this is ready to review on https://dev.data.humancellatlas.org/

Cheers,
D

**Comment by theathorn** [comment]
Please chnage the banner text to read:
This is a test environment and periodically may be unavailable and/or may contain test data.

Can you also change the background color to be a reddish/warning color that stands out more?
The font of the text could be a little larger too..

**Comment by theathorn** [comment]
Approved.
Does this apply automatically to all environments *except* Production?

**Comment by NoopDog** [comment]
yes should only be on lower environments.
