### ISSUE TITLE
Add banner to prod portal to show site is in beta

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-portal#303]
Add banner from staging site to prod site as well to help users know that data, content, features may change.  

This is important because the prod address may get passed around beyond our immediate beta testers (and we want to make sure everyone realizes it's under construction)

**Comment by theathorn** [comment]
@adriennes How about "This is a Beta test environment and periodically features may change or be unavailable"?

**Comment by adriennes** [comment]
Sounds good to me! We might also want to add, "... and periodically features, content, or **data** may change or be unavailable"

**Comment by frano-m** [comment]
@theathorn - just checking you want uppercase 'B' in 'Beta'?

**Comment by theathorn** [comment]
I suggest a lower case "b" for "beta".
It would be nice if the sentence fitted in 1 line - currently "unvailable is on a separate line".

**Comment by NoopDog** [comment]
@frano-m see above. Thx

**Comment by theathorn** [comment]
@frano-m Please capitalize "OK" or use "Okay".
