### ISSUE TITLE
Outdated URL for data download instructions on prod

### ISSUE THREAD

**Issue by gabsie** [DataBiosphere/data-portal#306]
Hi, 
One of the beta testers reported that this URL is a 404.
Haven't found out where she came from to land there.
https://prod.data.humancellatlas.org/learn/userguides/accessing-data/using-the-cli-to-access-data

Can we please check where it was used and get it updated, please?
Thanks
Gabby

**Comment by theathorn** [comment]
This is covered by humancellatlas/data-browser#373.
