### ISSUE TITLE
Downloading a manifest doesn't seem to work right in Safari

### ISSUE THREAD

**Issue by jodihir** [DataBiosphere/data-portal#316]
One of the beta testers used Safari to try to download a manifest and expected tsv/csv, and it opened as an html file.

**Comment by jodihir** [comment]
trying to add to feedback repo, not this one.

**Comment by theathorn** [comment]
Issue moved to [HumanCellAtlas/data-browser #404](https://github.com/HumanCellAtlas/data-browser/issues/404) via [**ZenHub**](https://www.zenhub.com/)
