### ISSUE TITLE
Pagination is not working correctly

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#329]
I am still working out if this is a client side issue or if there is a problem with Azul as well.  There may be a problem with both.

In any case, if you go to the projects tab in dev and go forward a page and then go back, you do not get back to where you started.

Will update this with any dependency on Azul if I find one.

**Comment by theathorn** [comment]
Issue moved to [HumanCellAtlas/data-browser #422](https://github.com/HumanCellAtlas/data-browser/issues/422) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ambrosejcarr** [comment]
I believe that pagination is still not working correctly. 

"Profiling of CD34+ cells from human bone marrow to understand hematopoiesis" shows up on both pages, and "1M immune cells" shows up on neither. The latter is particularly problematic, as it's one of our "flagship" studies.
