### ISSUE TITLE
In direct file download Image, PDF, txt files open inline instead of downloading

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#331]
To to fix this, we need content-disposition header set on the object in the download bucket by DSS as well as the file name.

Need to create a ticket in DSS and make this dependent on that tickets..

**Comment by NoopDog** [comment]
Shoot @theathorn can you move this to data browser please.

**Comment by theathorn** [comment]
Issue moved to [HumanCellAtlas/data-browser #423](https://github.com/HumanCellAtlas/data-browser/issues/423) via [**ZenHub**](https://www.zenhub.com/)
