### ISSUE TITLE
Make more space under markdown images

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#333]
We are getting some markdown images now which is great but you can see in the image below that the "Install" section is bumped up against the image. Can we pad that a little bit so there is more space (the final frontier) between the image and the next heading? Thanks!

![Screen Shot 2019-01-17 at 1.12.28 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/7768be53-7741-46e0-8c3f-3afe5f7829ee)

You can see images under all the "visualization tab" items.

**Comment by frano-m** [comment]
@NoopDog 

Normally a markdown image is wrapped inside a paragraph - which is adequately spaced with paragraph margins.

The above page utilised html to render the image (example below):

```
<a href="https://gxa.github.io/anatomogram-demo" target="_blank">
  <img src="../_images/visualization/anatomogram.png" width=200/>
</a>
```

Also the page used html to create a `mailto:` link:

```
Irene Papatheodorou (<a href="mailto://irenep@ebi.ac.uk">irenep@ebi.ac.uk</a>)
```

I have replaced all html with markdown:

```
[![Anatomogram](../_images/visualization/anatomogram.png)](https://gxa.github.io/anatomogram-demo)
```

and

```
Irene Papatheodorou ([irenep@ebi.ac.uk](mailto:irenep@ebi.ac.uk))
```

These files have been modified accordingly:
- anatomogram.md
- ideogram.md
- igv.md
- morpheus.md

I've also installed https://www.npmjs.com/package/gatsby-remark-external-links to allow for the markdown images to open to a new page.  I've added an option to ``gatsby-remark-images`` to allow the image to be linked to an external site: `linkImagesToOriginal = false`.
