### ISSUE TITLE
Learn link to API Documentation is broken

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#339]
In "Learn / Introduction" the "Using The Data" has a link to "in the API documentation" that gets a 404 error.

The link points to https://dev.data.humancellatlas.org/develop/api-documentation/data-store-consumer-api instead of https://dev.data.humancellatlas.org/learn/api-documentation/data-store-consumer-api.

**Comment by jodihir** [comment]
I fixed this using the link you provided.
