### ISSUE TITLE
Show "no modules" when file modules has no metadata

### ISSUE THREAD

**Issue by frano-m** [DataBiosphere/data-portal#343]
![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/7811395f-29cd-4381-9caa-651f967e2166)

**Comment by NoopDog** [comment]
@frano-m I think it was show "no modules" instead of hiding it. Thx

**Comment by frano-m** [comment]
@NoopDog yes, sorry - fixed!
