### ISSUE TITLE
M1.1: Provide availability monitoring and downtime alerting of data portal

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#345]
@morrisonnorman commented on [Fri Dec 07 2018](https://github.com/HumanCellAtlas/dcp/issues/230)

Relates to:
M1.1: Provide availability monitoring and downtime alerting of data portal.
[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

---

@morrisonnorman commented on [Tue Dec 11 2018](https://github.com/HumanCellAtlas/dcp/issues/230#issuecomment-446205671)

@theathorn Please can you comment on the status of this epic and link any open issues from your team board. Thanks!

---

@theathorn commented on [Tue Dec 11 2018](https://github.com/HumanCellAtlas/dcp/issues/230#issuecomment-446429260)

Issues linked.

**Comment by sampierson** [comment]
Closing in favor of HumanCellAtlas/dcp#281 and HumanCellAtlas/dcp#66
