### ISSUE TITLE
M3.5: Ensure that the data portal recovers from downtime responsively (to meet 95% uptime objective, and to avoid more than 24 hours constant downtime)

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#350]
@tburdett commented on [Tue Dec 04 2018](https://github.com/HumanCellAtlas/dcp/issues/205)

**Comment by sampierson** [comment]
I'm closing this epic tickets.  Availability is something you architect for up front, then measure in operation and correct as necessary.
