### ISSUE TITLE
Review HCA repositories and verify that the list of readers/writers is following principle of least access

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/data-portal#370]
The HumanCellAtlas GitHub teams have been restructured.
To ease the transition to this structured world, everyone is currently in a team called "HCA" that has WRITE access to all repos.  We want to move away from this.

Each component team lead needs to audit the GitHub teams that have access to their repos.
Ensure only appropriate teams (e.g. CZI, UCSC, etc) have write access to your component's repos.
Ensure that you approve of any collaborators.
Then remove access from team HCA.

**Comment by theathorn** [comment]
Hannes will create Azul group and hand this ticket back to Dave.

**Comment by hannes-ucsc** [comment]
https://github.com/orgs/HumanCellAtlas/teams/orange/members

**Comment by NoopDog** [comment]
HCA Team is removed
Orange and Clever Canary Teams are added.

@theathorn is there anything else that needs to be done for this or can this be closed?

Cheers,
Dave

![Screen Shot 2019-06-06 at 11.45.35 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/c943956b-1b30-4137-b95a-c92984eb9430)
