### ISSUE TITLE
HTML heading sizes should reflect organization of page elements on Home

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-portal#390]
HTML heading sizes are important for users utilizing screen readers to navigate the Data Portal.  
We should make sure that H1, H2, H3 levels correspond to the organization of the information on the page.  

Specific issues for Home page:
- Items in "blue bar" should not be H1 
- Text describing the HCA should not be H1
- "Start Exploring", "What is the HCA" sections should be H2

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
