### ISSUE TITLE
Add facet for sequencing_protocol.paired_end

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#399]
As a consumer of HCA data, I need to know whether a Smart-seq2 dataset is paired-end or not in order to  be sure that my workflow, which only analyzes paired-end SS2 data, will work.

As a consumer of HCA data, I need to be able to find only paired end data because I want to be able to have higher confidence in the results of my analysis, and paired end data offers higher coverage of transcripts than single end.

This will also help us signify if the data is processable by the matrix service.

**Comment by theathorn** [comment]
Issue moved to [HumanCellAtlas/data-browser #551](https://github.com/HumanCellAtlas/data-browser/issues/551) via [**ZenHub**](https://www.zenhub.com/)
