### ISSUE TITLE
Capture appropriate alerts and audit trails so we can handle detected attacks and understand the consequences of emergent threats and breaches

### ISSUE THREAD

**Issue by stahiri** [DataBiosphere/data-portal#408]
As specified in the [Q2 Roadmap] (https://docs.google.com/spreadsheets/d/1iAL2JR3ndgMmYwojUU0kU8Pm7B7ycRLt_973seREd3M/edit#gid=1107068822&range=C10).

We need appropriate alerts and audit trails so we can learn about and appropriately handle detected attacks and understand the consequences of emergent threats and breaches. This includes being able to know when an attack is taking place and being able to see in the logs what the attack entailed (what attacker accessed, changed, etc.).

__Deliverable__:
Ensure each component captures audit logs for the following types of events (as appropriate):
• Server alerts and error messages
• User log-on and log-off (successful or unsuccessful)
• System administration activities
• Modification of privileges and access
• Modifications to the application
• Application alerts and error messages
• Configuration changes
• Account creation, modification, or deletion

**Comment by stahiri** [comment]
@hannes-ucsc What would you expect the cost of this task to be (using the t-shirt sizing guidelines)?

**Comment by hannes-ucsc** [comment]
> __Deliverable__:
Ensure each component captures audit logs for the following types of events (as appropriate):
• Server alerts and error messages

Azul is based on Lambda and all logs are written to CloudWatch. We use API Gateway to front the Lambdas and it logs all requests, failed and successful ones.

> • User log-on and log-off (successful or unsuccessful)

Users don't log in to our application. All access is anonymous.

> • System administration activities

Our infrastructure is on AWS where CloudTrail logs all API actions.

> • Modification of privileges and access

Our infrastructure is on AWS where CloudTrail logs all IAM API actions.

> • Modifications to the application

In production, the app can only deployed by me or from Gitlab (our Gitlab instance) and deployment from Gitlab can only be triggered by committing to the `prod` branch and pushing it to both Gitlab and Github. Therefore, modifications to the applications are tracked in the Gitlab repository. The Gitlab build will fail if the commit doesn't also exist on Github. Therefore, modifications to the app are tracked as commit on Github.

> • Application alerts and error messages

Same as server alerts above.

> • Configuration changes

All configuration is hosted in the source repository on Github/Gitlab.

> • Account creation, modification, or deletion

Same as _Modification of privileges and access_ above.

**Comment by hannes-ucsc** [comment]
@stahiri , I consider this complete. Feel free to reopen if you feel any of this isn't sufficiently addressed.
