### ISSUE TITLE
Standardize error response format 

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-portal#442]
We are currently receiving a variety of error response formats depending on the response status code. For example:

#### Response status code 400
```
{
    "Code": "BadRequestError",
    "Message": "BadRequestError: 46c58e08-4518-4e45-acfe-bdab2434975dxxx is not a valid uuid."
}
```
#### Response status code 500

```
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
```

#### Response status code 503 (`/health` end point)
```
{
    elastic_search: ...,
    indexer: ...,
    queues: ...,
    unindexed_bundles: 0,
    unindexed_documents: 0,
    up: true
}
```

Can we unify the error response format across error codes?

**Comment by NoopDog** [comment]
closing as this is moved to Azul repo.

https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/databiosphere/azul/1208
