### ISSUE TITLE
Add "Draft Mode" for documents

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#444]
Add a field to the front matter

```
---
path: "/guides/userguides/why-i-left-the-woods"
date: "2019-05-14"
title: "Why I Left the Woods"
subTitle: ""
draft: true
---
```

Then for local, and dev environments show the "draft" = true items in the navigation if they are added to the sitemap.

For integration, staging, and prod, do not show the draft documents in the navigation even if they are listed in the site map.

This lets us avoid having branches per environment and the associated merging while also enabling us to create stub doc for people to work on.

So that we do not have to go back and add the `draft` to all the other documents, if it is not specified on a doc, we assume its "false".  So any existing docs will show in all environments. 

We will still need to use pull requests for modifying documents. The "Draft Mode" will smooth out the flow of having new docs sit on a branch until they are completed and reviewed.

**Comment by matthewspeir** [comment]
This sounds like an excellent idea. Is there an example of this implemented on dev already? Or is this something you're planning on rolling out?

Thanks!

**Comment by NoopDog** [comment]
Planning on rolling out.. wanted to see if the team was ok with it before moving along to far.

**Comment by matthewspeir** [comment]
Awesome. Well, I'm certainly in favor of anything that makes something simpler.
