### ISSUE TITLE
Add data lifecycle diagram to Guides>HCA Data Lifecycle page

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-portal#447]
Add data lifecycle diagram to Data Lifecycle page in Guides section of Data Portal. 
Assets: https://drive.google.com/drive/u/0/folders/1Kwmh8_TNUp8ZBd_Gt4K6tDjBFPPGVE1P

**Comment by theathorn** [comment]
Dup of https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-content/203
