### ISSUE TITLE
Replace smartseq2 diagram

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-portal#448]
Replace the smartseq2 diagram on Pipelines > Smartseq2 Workflow > Pipeline details with diagram in this folder: https://drive.google.com/drive/u/0/folders/19WjakQnz3y61wA73UC-gRcdi7lcoZJve

**Comment by theathorn** [comment]
Dup of https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-content/279
