### ISSUE TITLE
Replace Optimus diagram 

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-portal#449]
Replace diagram on Pipelines > Optimus Workflow > Optimus Modules Summary with diagram in this folder: https://drive.google.com/drive/u/0/folders/10fXz52Ux49qDHCZg0a_q1Dz0PEky1WOK

**Comment by theathorn** [comment]
Dup of https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-content/279
