### ISSUE TITLE
Determine Hosting Setup for Vanilla Forums

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#45]
Shall we: 

1. Subscribe to the hosted solution. (probs this one?)
1. Deploy and configure ourselves.
1. Use the Broad instance?

https://vanillaforums.com/en/plans/

**Comment by happyimadesignr** [comment]
I was told this is now a stretch goal decided by PMs.

**Comment by happyimadesignr** [comment]
I'll let you track this @theathorn

**Comment by theathorn** [comment]
May not use Vanilla Forums. Use #19 to track instead.
