### ISSUE TITLE
Replace icons on home page and contribute page

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-portal#450]
Replace icons on Data Portal Home "What is the data portal?" section and Contribute page "Data Contribution Process" section with icons in this folder: 
https://drive.google.com/drive/u/0/folders/1MBFlTO1jQi70CMl1S_aunOd20a6VClpt

**Comment by MillenniumFalconMechanic** [comment]
[https://app.zenhub.com/files/124946282/1f8867ae-b448-401a-8b12-2c27fd7f380b/download](https://app.zenhub.com/files/124946282/1f8867ae-b448-401a-8b12-2c27fd7f380b/download)

**Comment by frano-m** [comment]
@NoopDog can you please advise for:

`https://dev.data.humancellatlas.org/contribute#data-submission-process`

a) Currently the images have text associations:
i) will we retain the text, and if so
ii) can you please confirm the title/text for image 3 remains the same?

b) The images sizes as per the specification will be too large - content max width is 640px.
4 x images @ 168px + 3 x arrows @ 27px = 753px.  Gatsby will shrink image to size but:
i) the text will also shrink, and
ii) we won't be achieving the desired image size as per specification.

Thanks.

**Comment by frano-m** [comment]
@MillenniumFalconMechanic completed first pass - home page only. Will do contribute page when I have the required information to proceed.

**Comment by NoopDog** [comment]
@frano-m @MillenniumFalconMechanic 

Regarding questions above, just shrink to fit for now to unblock this. 

Regarding title text for image 3 can you add both the new and old images and text to this ticket so I can see if the text needs to be updated.

D

**Comment by frano-m** [comment]
@NoopDog see below

current - image 3 and text:
![image](https://user-images.githubusercontent.com/18710366/62501670-3396b800-b82f-11e9-98e3-1d69869796fb.png)

new image 3
![image](https://user-images.githubusercontent.com/18710366/62501709-63de5680-b82f-11e9-926e-277604a2a5a2.png)

**Comment by janeecely** [comment]
@NoopDog @frano-m @MillenniumFalconMechanic 

There was an error in the guide for icons 3 and 4. [Corrected guide has been uploaded](https://drive.google.com/open?id=16YJGjX4qnZsN936guPkvManNqG5NvrsO), screenshots of correction below. Needed icons are already within delivered icon set. 

<img width="437" alt="Screen Shot 2019-08-06 at 11 16 26 AM" src="https://user-images.githubusercontent.com/27827447/62566014-defa3980-b83c-11e9-8a57-97b11c9a5069.png">
<img width="436" alt="Screen Shot 2019-08-06 at 11 16 30 AM" src="https://user-images.githubusercontent.com/27827447/62566026-e4f01a80-b83c-11e9-8517-197bf3667fbe.png">

**Comment by MillenniumFalconMechanic** [comment]
Brilliant, thank you @janeecely.
