### ISSUE TITLE
Fix Preview site

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-portal#457]
As an end user I would like the preview site's download scripts to work so that I can download the bundles associated with a project.

Definition of done:
(one possible solution)
leave the preview site in place
Change out the links to the download scripts (that no longer work) to be links to the prod browser, with the relevant project selected. 
Add a link on the preview site to the download manifest instructions on the prod site
Leave links for the matrix data that exist on the preview site as they are still relevant. 

(Note that we have had 2 users try to use the preview site and fail because the bundles had been deleted. )

**Comment by NoopDog** [comment]
@kozbo what shall we do with the link to the metadata spreadsheet? Shall we replace it with a link to the metadata CSV available on the browser?

**Comment by kozbo** [comment]
yes, use the metadata CSV from the browser, thanks

**Comment by NoopDog** [comment]
@jessebrennan @kozbo are these instructions still accurate with the latest version of the CLI?

https://prod.data.humancellatlas.org/guides#downloading-a-data-manifest

What would be the command to run once the CLI is installed to download the set of files in a manifest?

**Comment by NoopDog** [comment]
@kozbo just checking that these are the 3 relevant projects:

## Census of Immune Cells
https://prod.data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22projectTitle%22%2C%22terms%22%3A%5B%22Census+of+Immune+Cells%22%5D%7D%5D

## Ischaemic Sensitivity of Human Tissue
https://prod.data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22projectTitle%22%2C%22terms%22%3A%5B%22Ischaemic+sensitivity+of+human+tissue+by+single+cell+RNA+seq%22%5D%7D%5D

## Melanoma Infiltration of Stromal and Immune Cells
https://prod.data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22projectTitle%22%2C%22terms%22%3A%5B%22Melanoma+infiltration+of+stromal+and+immune+cells%22%5D%7D%5D

**Comment by kozbo** [comment]
Yes, exactly. Thanks

**Comment by NoopDog** [comment]
@kozbo these changes are pushed to staging but we need to wait for a manual deploy as the deploy keys are expired (we have not deployed in over a year). 

Will ping you for review once the site is deployed to staging.

Cheers,
D

**Comment by NoopDog** [comment]
@kozbo first pass of updates for this on are here: https://preview.staging.data.humancellatlas.org/

for your review.

Let me know if you see anything that needs to be updated before we deploy this to prod.

Cheers,
Dave

**Comment by kozbo** [comment]
Looks good to me. 
why not link to the metadata file in the project rather than have the link on the preview site?

**Comment by theathorn** [comment]
Looks good to me - let's promote to the actual preview site.

**Comment by NoopDog** [comment]
@kozbo @theathorn this is deployed to prod. Cheers, D

https://preview.data.humancellatlas.org/
