### ISSUE TITLE
Setup Integration and Staging Travis Build and Buckets

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#47]
We need the same setup as dev for:

- [ ] https://staging.data.humancellatlas.org
- [ ] https://integration.data.humancellatlas.org

Thanks!

**Comment by theathorn** [comment]
Do we have an ETA for this?

**Comment by NoopDog** [comment]
@parthshahva thanks for setting up the stage environment for this. The team is asking also for an integration environment can you set this up for us this week?

Thanks, Dave

**Comment by theathorn** [comment]
@hannes-ucsc and @alex-hancock Is this in your purview?

**Comment by hannes-ucsc** [comment]
I don't think so. This is the portal, not the browser or the backend (Azul).

**Comment by parthshahva** [comment]
It's not my in domain currently, but its probably easiest since I set up the staging env. It's prioritized for this week.

**Comment by parthshahva** [comment]
This is done. integration.data.humancellatlas.org is deployed and building from gatsby alongside dev. Integration branch was cut off of head of develop. Staging is still building off of npm. cc @NoopDog @theathorn
