### ISSUE TITLE
Design display of summary stats plots on portal

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#470]
Diagrams are:

1. Genes that yield the highest fraction of counts in each single cell, across all cells (i.e., rows). Plot and data table.

1. Identify highly-variable genes (plot) and extract the table of the top 20 genes

1. Violin plot of the computed quality measures (plot)

Also link to Jupyter notebooks describing how the per project summary plots were made.

Spec document:

https://docs.google.com/document/d/1l-_Er-mltFMuaPRkTPw9YYjUMuijqacZWdNCag3mOGU/edit

**Comment by NoopDog** [comment]
Hi @Dave Rogers, there are currently two files uploaded to `aws s3 ls s3://dev.project-assets.data.humancellatlas.org/project-assets/project-stats/`. I was mostly concerned with getting them from the matrix service, process them, and uploading the images. I suppose we should give meaningful titles to each image, for example containing the project name and version/date/?...

mkrause  [2 hours ago]
Check out https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html. One of the figs made by the command shown in line 7, the other from the command in line 18.

mkrause  [2 hours ago]
I named them by the ScanPy method name that created them.

mkrause  [2 hours ago]
I was't sure what image format you prefer, for now those in saved as `png`. Alternatives are `svg` and `pdf`. (edited)

mkrause  [2 hours ago]
I will create another type, shown here https://scanpy.readthedocs.io/en/latest/api/scanpy.pl.stacked_violin.html#scanpy.pl.stacked_violin.

**Comment by NoopDog** [comment]
wrong repo, closing in favor of https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-browser/770
