### ISSUE TITLE
`null` in summary response cause portal to go blank

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-portal#480]
Recent Azul changes fixed a bug that caused `null` values to be artificially suppressed in the /summary response. This bug is now fixed and the resulting `null` values in the summary response cause a null pointer exception in the Data Portal.

<img width="1132" alt="Screen Shot 2019-08-06 at 7 17 51 PM" src="https://user-images.githubusercontent.com/5143256/62589806-446f1a00-b87f-11e9-9b08-b59b1a0be4c6.png">

<img width="1156" alt="Screen Shot 2019-08-06 at 7 13 14 PM" src="https://user-images.githubusercontent.com/5143256/62589808-446f1a00-b87f-11e9-8498-0319c0d41d01.png">

<img width="1153" alt="Screen Shot 2019-08-06 at 7 16 15 PM" src="https://user-images.githubusercontent.com/5143256/62589809-446f1a00-b87f-11e9-8511-fcad16a09b83.png">

**Comment by NoopDog** [comment]
Thanks @hannes-ucsc will fix. By the way, what is the meaning of 0:null ? Does this mean the organ type was specified as "null" (as opposed to being undefined)?

**Comment by hannes-ucsc** [comment]
It's an array with the first and only element being `null`. The zero is just added by the browser's inspect UI.

**Comment by NoopDog** [comment]
Yea, I mean what is the meaning of the null value in the array?

**Comment by hannes-ucsc** [comment]
For organTypes, the presence of `null` in the summary means that there are samples that don't have an organ.

For, cellCountSummary

<img width="277" alt="Screen Shot 2019-08-06 at 7 27 43 PM" src="https://user-images.githubusercontent.com/5143256/62590146-484f6c00-b880-11e9-8167-e2ae559dfa47.png">

indicates that there are 1,758 cell suspensions without an associated organ and that the sum of the `total_cell_count` property of each of those cell suspensions equals 4.5 million cells.

**Comment by NoopDog** [comment]
OK great thanks.

@frano-m we need to change null to "Unspecified" before we try to do the camel case fix.
