### ISSUE TITLE
Capture Code Coverage Metrics

### ISSUE THREAD

**Issue by rhiananthony** [DataBiosphere/data-portal#482]
This work has shifted to Q4 as NICE TO HAVE work and, as such, may or may not be completed during Q4. It is an objective in the ~Q3~ Q4 epic [Improving Deployment Process for Infrastructure](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/420)

## Definition of success
We have 85% code coverage for our unit and integration tests. 

*Please note that there is active discussion about the framing of this definition. This ticket will be updated with any alterations.*

**Comment by theathorn** [comment]
Note from Azul ticket: "Code coverage is tracked by Travis via Codecov and Coverage.io on all branches".

**Comment by stahiri** [comment]
@theathorn I've updated the description of this ticket to reflect the objective that it is associated with, which is somewhat misleading based on the ticket title.

**Comment by chmreid** [comment]
In addition to framing what target we want for code coverage, it would be helpful to ensure developers actually understand what these code coverage reports mean. I find the code coverage reports from CodeCov.io to be confusing, and often incorrect or misleading. The documentation barely mentions how to read the reports or why the reports might look weird (see [Unexpected Coverage Changes](https://docs.codecov.io/docs/unexpected-coverage-changes)). All of the examples in their documentation are less than 5 lines, so easy to understand but not applicable to real world PRs.

Ideally we could give developers a wiki page with a cheatsheet/guide (like, "here's what you should be on the lookout for when reading code coverage reports," "here is a common misconception about the reports," etc.). Super ideally, this guide would be provided by codecov.io

**Comment by stahiri** [comment]
Re-assigning this ticket to a separate code coverage epic that is iceboxed, as it's a Q4 stretch goal.
