### ISSUE TITLE
Allow for click to enlarge images on the data portal

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#485]
The channel is narrow to support readability but this can make images small and hard to read.

Lets use one of the gatsby plugins to pop open the images to a larger frame on click.

**Comment by NoopDog** [comment]
There are additional comments regarding this in this closed dupe:

https://github.com/HumanCellAtlas/data-browser/issues/824

**Comment by frano-m** [comment]
@MillenniumFalconMechanic resolved by PR https://github.com/HumanCellAtlas/data-portal/pull/513/files
