### ISSUE TITLE
Single-Cell Signature Explorer

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#490]
@FredPont commented on [Wed Jul 31 2019](https://github.com/HumanCellAtlas/data-portal-content/issues/298)

Thank you for submitting a visualization component package to the HCA DCP Methods Registry!

To expedite your package's addition to https://prod.data.humancellatlas.org/analyze/visualization,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your package's detail page ([example](https://prod.data.humancellatlas.org/analyze/visualization/anatomogram)).

[Required](https://prod.data.humancellatlas.org/contribute/analysis-tools-registry#package-submission-field-details):
- Tool title: Single-Cell Signature Explorer
- Contact name: Frédéric PONT
- Contact email: frederic.pont@inserm.fr
- Who to attribute: Frédéric PONT
- Code repository URL: https://sites.google.com/site/fredsoftwares/products/single-cell-signature-explorer
- Affirm code is free and open source with license available in code repository: [x] (fill in as [x] to affirm)
- Short description: Single-Cell Signature Explorer is a package of softwares dedicated to high throughput signature exploration in single-cell RNAseq analysis.

[Optional](https://prod.data.humancellatlas.org/contribute/analysis-tools-registry#optional-fields-for-methods-and-visualizations):
- Long description: Single-Cell Signature Explorer is a package of four softwares dedicated to high throughput signature exploration in single-cell RNAseq analysis. It is a tool for qualitative and high-throughput scoring of any gene set-based signature at the single cell level and its visualization using t-SNE or UMAP. By scanning datasets for single or combined signatures, it rapidly maps any multi-gene feature.
![screenshot](https://user-images.githubusercontent.com/53525948/62217270-a248c100-b3aa-11e9-8e88-8e92c1d776a1.png)

Reference : Frédéric Pont, Marie Tosolini, Jean J Fournié, Single-Cell Signature Explorer for comprehensive visualization of single cell signatures across scRNA-seq datasets, Nucleic Acids Research, , gkz601, https://doi.org/10.1093/nar/gkz601

---

@matthewspeir commented on [Wed Jul 31 2019](https://github.com/HumanCellAtlas/data-portal-content/issues/298#issuecomment-516988418)

Thank you, @FredPont, for submitting your tool to the HCA DCP tools registry. We will review the information you have provided and let you know if we have any questions.

**Comment by matthewspeir** [comment]
Hello, @FredPont! 

Thank you again for submitting a tool to the HCA DCP Methods Registry. I apologize for the delay in getting back to you. After reviewing your tool against our [registry standards](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards), there are a few issues with adding your tool to the HCA DCP portal:

(1) While your tool may be open source, we require it to be available in a public repository on GitHub. See the '[Be Free and Open Source](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards#be-free-and-open-source)' section on our standards page.

(2) It does not appear that your tool uses containers or modules as described under '[Use Containers and Modules](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards#use-containers-and-modules)'.

(3) Your tool does not appear to be registered in an upstream repository as described under the '[Register Upstream](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards#register-upstream)' section of our standards.

(4) It's not clear that your tool comes with test data as described under ['Provide Testing Data'](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards#provide-testing-data).

From a quick skim, it seems the "Scorer" and "Merger" components of "Single-Cell Signature Explorer" (the components written in Golang) would fall into the [Methods](https://data.humancellatlas.org/analyze/methods) category. We recognize that golang doesn't have an upstream repository akin to bioconductor or bioconda, so, we may relax this one requirement in your case if you can containerize these tools as described under ['Use Containers and Modules'](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards#use-containers-and-modules) and fulfill the rest of the requirements.

**Comment by FredPont** [comment]
Hi @matthewspeir !

Thank your for your comments which we found surprising since It appears that 
1- our tool is open source and publicly available since may 2019 from https://sites.google.com/site/fredsoftwares/products/single-cell-signature-explorer 
where it has been download more than 150 times by most US universities.
2- we agree and we do not plan to use containers. Indeed we provide ready to use executable for Go softwares.
4- The available softwares already include testing data. These later have been fully tested while reviewing our submitted manuscript which is now published in Nucleic Acids Research, gkz601, https://doi.org/10.1093/nar/gkz601

Theses tools are now widely used in our institute and in other labs involved in producing scRNAseq datasets of Human tissues, and led to several publications (e.g Proc Natl Acad Sci U S A. 2019 Jun 11;116(24):11906-11915. doi: 10.1073/pnas.1818488116. Epub 2019 May 22.). Our politics is to make these extremely popular tools fully available and readily usable to any biologist/medical scientist as they currently are. It is thus upon your own decision to provide it through HCA or not.

Regards

Fred

**Comment by matthewspeir** [comment]
Hello, @FredPont.

Thank you again for submitting a tool to the DCP Methods Registry. The [standards](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards) are required to be met before your method can be listed in our registry. If you do not plan to fulfill these requirements, unfortunately, we cannot list your tool in our registry. I am going to close this ticket for now. Please do open a ticket in the future if you would like to resubmit this tool or another one that meets these registry standards.
