### ISSUE TITLE
Add https://humancellatlas.usegalaxy.eu portal

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#491]
@pcm32 commented on [Fri Aug 09 2019](https://github.com/HumanCellAtlas/data-portal-content/issues/305)

Thank you for submitting a portal to the HCA DCP Methods Registry!

To expedite your portal's addition to https://data.humancellatlas.org/analyze,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your portal's detail page ([example](https://data.humancellatlas.org/analyze/portals/asap)).

Required:
- Tool title: Human Cell Atlas Galaxy Instance
- Contact name: Pablo Moreno
- Contact email: pmoreno@ebi.ac.uk
- Who to attribute: P Moreno, N Huang, J Manning, S Mohammed, C Talavera-Lopez, K Polanski, W Bacon, B Gruening, H Rasche, K Meyer, S Teichmann, A Brazma, I Papatheodorou
- Portal URL: https://humancellatlas.usegalaxy.eu
- Short description: The Human Cell Atlas Galaxy instance contains tools for Single Cell analysis and interactive visualisation (UCSC CellBrowser). It can import matrix data from the Human Cell Atlas and the EBI Single Cell Expression Atlas, for re-analysis.

Optional:
- Long description: The Human Cell Atlas Galaxy instance contains tools for Single Cell Clustering (Scanpy, Seurat, Scater/SC3), Trajectories analysis (Scanpy, Monocle) and interactive visualisation (UCSC CellBrowser), allowing simple data analysis through the proven Galaxy user interface. It also includes facilities to import matrix data from the Human Cell Atlas and the EBI Single Cell Expression Atlas, for re-analysis. The clustering workflow for the release 6 of EBI Single Cell Expression Atlas are reproducible through this portal. The portal runs as part of the larger usegalaxy.eu infrastructure and has access to thousands of cores and terabytes of RAM and storage, kindly hosted by the U. of Freiburg, den.bi and Elixir.
- Logo or screenshot: https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/blob/develop/img/cell-browser.png

---

@matthewspeir commented on [Fri Aug 16 2019](https://github.com/HumanCellAtlas/data-portal-content/issues/305#issuecomment-522073629)

Hi, @pcm32. Thank you for submitting an analysis portal. We'll review that it meets our standards at https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards and get back to you soon.

**Comment by matthewspeir** [comment]
Helo, @pcm32.

Thank you again for submitting an analysis portal to the HCA Methods Registry. I apologize for the delay in getting back to you about the status of your submission. 

Can you provide more details about the following registry standards and how your submission fulfills these:
* For "[Be Free and Open Source](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards#be-free-and-open-source)", I can see that there is a Github repository for [usegalaxy](https://github.com/usegalaxy-eu), but is there one for your specific instance?
* For "[Use Containers and Modules](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards#use-containers-and-modules)", I see there is a [usegalaxy container in DockerHub](https://hub.docker.com/r/bgruening/usegalaxy), but it hasn't been updated for 4 years. Is there a Docker container for your usegalaxy instance?
* For "[Register Upstream](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards#register-upstream)", is the code for this portal available in some upstream repository like bioconda or bioconductor?
* For "[Document Installation and Usage](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards#document-installation-and-usage)", I see that each of the methods provides instructions on how to use them. Are there instructions for people who want to clone your usegalaxy instance and set up their own copy of it?
* For "[Provide Testing Data](https://data.humancellatlas.org/contribute/analysis-tools-registry/registry-standards#provide-testing-data)", is there a small test dataset that people can run through these various Galaxy methods.

**Comment by pcm32** [comment]
Hi @matthewspeir, 

> For "Be Free and Open Source", I can see that there is a Github repository for usegalaxy, but is there one for your specific instance?

There is a Github repo for the orchestrated container (to be used in Kubernetes or Docker compose; it contains all tool definitions): https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary

> For "Use Containers and Modules", I see there is a usegalaxy container in DockerHub, but it hasn't been updated for 4 years. Is there a Docker container for your usegalaxy instance?

To be used as a container you need to follow instructions as explained in the github site above. Please note that while this will run on a single machine with either Docker compose (following instructions in docker-galaxy-stable compose part https://github.com/bgruening/docker-galaxy-stable/tree/master/compose) or through Minikube (see instructions here https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary), this is really meant to be run on larger Kubernetes installations (a proper k8s cluster). All of the tools are used as individual containers, resolved automatically by Galaxy through bioconda and biocontainers.

> For "Register Upstream", is the code for this portal available in some upstream repository like bioconda or bioconductor?

All tools in the Galaxy instance are bioconda packages and each bioconda package will also have an automatically generated mulled container. All the Galaxy tools are also present in the Galaxy Toolshed under user ebi-gxa https://toolshed.g2.bx.psu.edu/view/ebi-gxa for direct installation on any Galaxy instance. Each Galaxy instance, based on setup, will decide whether to use the bioconda package or the mulled container, for each tool.

> For "Document Installation and Usage", I see that each of the methods provides instructions on how to use them. Are there instructions for people who want to clone your usegalaxy instance and set up their own copy of it?

Again https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary should contain these.

> For "Provide Testing Data", is there a small test dataset that people can run through these various Galaxy methods.

Some of the Galaxy tools in the instance have test methods and they include test data. However, given the size of some of the test datasets, and our intention to reduce the container size, not all are included.

I hope that this is good enough!

Thanks for reviewing!

**Comment by matthewspeir** [comment]
Hi, @pcm32!

Thanks for sharing all of this. Your portal appears to meet all of the registry standards. I'll work to add it to the 'portals' list on data.humancellatlas.org. I'll get back to you if I have any questions.

**Comment by theathorn** [comment]
@matthewspeir Please coordinate with @MillenniumFalconMechanic on this.

**Comment by matthewspeir** [comment]
Hi, @MillenniumFalconMechanic, it looks like I just need to add a markdown file that contains all of the information provided? Something like the one for UCSC Xena: https://github.com/HumanCellAtlas/data-portal/blob/develop/content/analyze/portals/ucsc-xena.md 

I'll also be sure to follow the steps Dave outlined in this [Slack message to the content-team](https://humancellatlas.slack.com/archives/CA53K2C3A/p1566235939038900):
>1) Make a PR against in the staging branch of the data-portal repo and request content review/approval from appropriate stakeholders
>2) Once the PR is merged after .5h or so on the staging.data.humancellatlas.org site.
>3) If it looks ok there, the data portal team will promote it to master.

**Comment by pcm32** [comment]
Hi everyone, is this viewable already or are we missing something that we need to provide? Just checking, thanks!

**Comment by matthewspeir** [comment]
Hi, Pablo! I've made a pull request that adds a page for your portal: #550, but it looks like it's still waiting on review/feedback before being merged in.

**Comment by NoopDog** [comment]
Hi @pcm32 we will merge this shortly. 

Cheers,
Dave

**Comment by NoopDog** [comment]
@MillenniumFalconMechanic @frano-m Howdy, can we get this added to the sitemap please?

The associated markdown pr is...

https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/humancellatlas/data-portal/550

You can just add to that. 

This goes in the portal section. 

Cheers,
Dave

**Comment by NoopDog** [comment]
@pcm32 this is now live

https://data.humancellatlas.org/analyze/portals/hca-galaxy-instance

**Comment by pcm32** [comment]
Thanks! I noticed that there are a few people missing on the attributions how can I add them?

**Comment by NoopDog** [comment]
@pcm32 Select the "improve this page" link at the bottom of the page and then use the github markdown editor to create a pull request.

Does that help?

Cheers,
D
