### ISSUE TITLE
Tweak CLI download instructions to reflect file store and layout changes

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#492]
@hannes-ucsc commented on [Tue Aug 13 2019](https://github.com/HumanCellAtlas/data-portal-content/issues/306)

Tweak https://data.humancellatlas.org/guides/quick-start-guide#using-the-cli-to-download-files-listed-in-the-manifest to reflect @jessebrennan's recent download changes.

For example, consider mentioning the `--layout` option and explaining the file store a little bit.

**Comment by theathorn** [comment]
Beta-2 feedback requested improved cli documentation.

**Comment by NoopDog** [comment]
closing cli is being sunset
