### ISSUE TITLE
internal QA - Fix or remove "Fat" from the list of organs

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-portal#494]
### Why
As a user, I would like to understand what is 'Fat' in the list of organs on https://ux-dev.data.humancellatlas.org/

Hovering on "Fat" doesn't show anything on the organogram however indicates that there are 5.9K cells of "Fat" in the HCA. 

Also when you click on it, it doesn't show any project but does load some headings which should not be there:
https://ux-dev.data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22organ%22%2C%22terms%22%3A%5B%22fat%22%5D%7D%5D

### Definition of Done
Either one:
 - [ ] Remove "Fat"
 - [ ] Fix the organogram and correct the link to the project

**Comment by theathorn** [comment]
Already removed.
