### ISSUE TITLE
internal QA - Include info about not accepting data from living EU donors in the Data Suitability - Criteria?

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-portal#495]
### Why
As a user, I would like to clearly see what type of data I can submit. Currently, because of European GDPR legislation, HCA can not take any data from alive EU donors. 

I think this should be discussed whether this is needed at this time.

### Definition of Done
 - [ ] add a statement about the inability to take data from alive EU donors to the Data Suitability Criteria

**Comment by theathorn** [comment]
@lauraclarke to suggest who can address this.

**Comment by NoopDog** [comment]
Obsolete
