### ISSUE TITLE
new package: scAlign

### ISSUE THREAD

**Issue by gquon** [DataBiosphere/data-portal#498]
Thank you for submitting a method package to the HCA DCP Methods Registry!

To expedite your package's addition to https://prod.data.humancellatlas.org/analyze/methods,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your package's detail page ([example](https://prod.data.humancellatlas.org/analyze/methods/sc3)).

Required:
- Tool title: scAlign
- Contact name: Gerald Quon
- Contact email: gquon@ucdavis.edu
- Who to attribute: Nelson Johansen, Gerald Quon
- Method-ready Docker image URL:
- Code repository URL: https://github.com/ucdavis/quontitativebiology/tree/master/scAlign
- Affirm code is free and open source with license available in code repository: [x ] (fill in as [x] to affirm)
- Language:  Python, R
- Upstream registry URL: 
- Test data location: https://github.com/ucdavis/quontitativebiology/tree/master/scAlign
- Basic command line usage:
- Command to validate installation:
- Short description: scAlign is a tool for integrating multiple single cell genomic datasets. Input datasets can represent different biological conditions, or batches. scAlign will estimate dataset-specific differences, visualize them, and remove them.

**Comment by NoopDog** [comment]
Have not heard back  in over a year. Closing.
