### ISSUE TITLE
Consumer API code documentation detailed docs

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-portal#500]
# Why
As a developer I would like to be able to see detailed API documentation for the Python bindings. This is beyond the Swagger docs that only document the web APIs

# Definition of Done
 - [ ] Provide a page like the read the docs page 
 - [ ] Provide a page that displays the Swagger documentation

**Comment by theathorn** [comment]
There is already linked from the "API Documentation" page which is sufficient for the Closed Beta.
Future enhancement is to dynamically import and format this content.

**Comment by diekhans** [comment]
Please, yes.  The DSS API is really hard to use from the documentation.  There are no concepts explained, and no definitions.   There is an API to collections, but no one has an idea what a collection is.

I have been told that you can have events on collections but the documentation doesn't say this.

**Comment by theathorn** [comment]
Obsolete DCP/1 issue.
