### ISSUE TITLE
Guides: Using the CLI to Access Data

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#501]
# Why
As a user I would like to know how to use the CLI to access data on the site.

# Definition of Done
 - Implement page
 - [ ] Slurp in the RTD pages for the CLI

**Comment by kozbo** [comment]
OK, I have moved the content over to the QSG page. I also shifted the content to point at the RTD pages for now.

Over to you @NoopDog , thanks!

**Comment by NoopDog** [comment]
Closing CLI is being sunset
