### ISSUE TITLE
Tertiary portal  hand-off documentation

### ISSUE THREAD

**Issue by jodihir** [DataBiosphere/data-portal#502]
The Portals Development Guide (https://dev.data.humancellatlas.org/develop/development-guides/tertiary-portal-development-guide/) says the following:

Hand-off Description - Coming Soon
Register for the Hand-off - Coming Soon

Please draft the content for this doc or docs if we/when we have it.

@theathorn  Can you assign this to the right person?

**Comment by theathorn** [comment]
https://editor.swagger.io/?url=https://raw.githubusercontent.com/DataBiosphere/azul/develop/rfc/portal-registration-api.yaml

**Comment by NoopDog** [comment]
Obsolete
