### ISSUE TITLE
Add a link to the data release policy under "Contribute"

### ISSUE THREAD

**Issue by jahilton** [DataBiosphere/data-portal#508]
# Why
As a data generator, I would like to understand the policies surrounding the data I am submitting to the DCP

# Definition of Done
 - a "Data Release Policy" header appears somewhere under https://data.humancellatlas.org/contribute & contains a link to https://drive.google.com/file/d/1kLR0OpEFqS9DdSqFZmM4b2ATFyvwpPum/view

OR

 - a "Data Release Policy" header appears somewhere under https://data.humancellatlas.org/contribute & leads to a portal page with the same content as the google doc

**Comment by theathorn** [comment]
Use same link as suggested in https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/humancellatlas/data-browser/881

**Comment by MillenniumFalconMechanic** [comment]
See also #916, #902.

**Comment by NoopDog** [comment]
Obsolete
