### ISSUE TITLE
Broken links in browser metadata section

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#509]
https://prod.data.humancellatlas.org/metadata/design-principles/schema_style_guide contains a broken link in the second to last paragraph

**Comment by NoopDog** [comment]
Removed the "improve this page links" above as they are a dupe of #484. Kept the other broken links.

**Comment by theathorn** [comment]
From "Design Principles" the links for "semantically versioned" and "Improve this page"  get 404 errors.

**Comment by NoopDog** [comment]
@theathorn the above links are now replaced in the lower environments with the correct URL to the metadata schema github branch  where the reference document is hosted. If you select the links on staging, integration and dev they should work now. Can you let us know if they look ok to you?

Cheers,
Dave

**Comment by theathorn** [comment]
All links look OK on staging.

**Comment by NoopDog** [comment]
Ok thanks for checking.
