### ISSUE TITLE
Tutorial on how to send search results to Terra

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#512]
There is a tutorial (on or pointed to from our “Guides” portal section) that a researcher can follow that will show them how to search and send results (could go with BAM files) to Terra. The tutorial will then show them how to do some basic analysis on the BAMs in Terra via a WDL workflow (could be the same super simple analysis that the first tutorial did).

**Comment by theathorn** [comment]
@kozbo Would like to see this completed in the Q3/M3 sprint so we can close out the parent dcp-337 Epic..

**Comment by kozbo** [comment]
@natanlao do you have enough info to complete this? It seems like you will need an account in Terra and some knowledge of how to run a workflow in that environment, and some advice on which workflow to run. Are you all set on these things? If not then I can pair you with someone who can help.

**Comment by natanlao** [comment]
@kozbo I would appreciate support.

**Comment by kozbo** [comment]
@DailyDreaming can you assist Natan on this task?

**Comment by chmreid** [comment]
Associated PR is #534
