### ISSUE TITLE
Remediate High vulnerabilities

### ISSUE THREAD

**Issue by Lilalamar** [DataBiosphere/data-portal#514]
Snyk reports 10 [**High** vulnerabilities](https://app.snyk.io/org/humancellatlas/project/3bc8502f-e123-4fce-b263-e8b68b82916f) in HumanCellAtlas/data-portal package.json file. Please remediate or, if applicable, document as a false positive finding. Please remediate by the end of Q3 Milestone 3.

**Comment by NoopDog** [comment]
@Lilalamar can you add me to the project?

https://app.snyk.io/org/humancellatlas/project/3bc8502f-e123-4fce-b263-e8b68b82916f

I get an access denied trying to view this.

Cheers,
D


```Unable to display this organisation
The organization does not exist, or you do not have permissions to access it.

If this problem persists, please contact support with reference ID  85c49a2f-ae44-4063-9099-ac33963162c9.
```

**Comment by NoopDog** [comment]
Also @Lilalamar github is showing no alerts. Can I ask you to confirm that the github alerts are setup correctly?

https://github.com/HumanCellAtlas/data-portal/network/alerts

Thank you.

**Comment by stahiri** [comment]
Hey @NoopDog, that's correct --- these particular vulnerabilities that have been reported by Snyk are not showing up in GitHub. @adrazhi did note that (1) GitHub and Snyk are independent, so may find different vulnerabilities, and (2) Snyk may have a higher rate of reporting false positives than GitHub, but we still want to work all of the reported Critical/High severity vulnerabilities. 

The GitHub alerts to seem to be appropriately configured --- @adrazhi and/or @rhiananthony, do you see anything that should be changed wrt the setup?

**Comment by NoopDog** [comment]
Thanks @stahiri @Lilalamar one more question. Should not Snyk be looking a the package-lock.json file (instead of the package.json). The package lock indicates the versions actually used rather than the range of allowed packages. Does the Snyk setup need to be updated.

**Comment by rhiananthony** [comment]
@NoopDog Snyk won't import the package-lock.json file. I do not see an error, but it doesn't seem to like the file for some reason. I reached out to ask Snyk's support team and didn't get much of a meaningful response. 

I think that you also were sent an invite to the Snyk org (dave@clevercanary.org?). Is there a different email that you'd like the invite to be sent to?

**Comment by NoopDog** [comment]
I have access now. Thanks.

**Comment by NoopDog** [comment]
Hi @Lilalamar the high vulnerabilities have been remediated for this repo.

Can you confirm and close?

Thanks @MillenniumFalconMechanic for working through this.

**Comment by NoopDog** [comment]
@Lilalamar I had to revert this change as we notice some functionality problems. 
I will re-introduce this after we fix and let you know. Moving out of "Review" for now and back to "in-progress".

**Comment by Lilalamar** [comment]
Sounds good @NoopDog . Thanks for the updates!

**Comment by NoopDog** [comment]
@Lilalamar Ok so high vulnerabilities should be resolved on master now.  Can you take a look and close if it looks ok?

Thanks,
Dave

**Comment by Lilalamar** [comment]
@NoopDog confirmed. This high vulnerability has been resolved. Closing ticket. Thank you all!
