### ISSUE TITLE
Document updated content release workflow 

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#516]

**Comment by ambrosejcarr** [comment]
Not to suggest that documentation isn't needed, but I was playing with the DCP and found the "improve this page -> github markdown file that I can fork/PR" workflow to be very intuitive. Nice work. 👍 

I also found a very large amount of out of date content, and wonder if there is an opportunity for process improvement here. This workflow feels simple enough that teams could be made responsible for keeping content related to their services up to date. Is this the intention?

**Comment by NoopDog** [comment]
Obsolete.
