### ISSUE TITLE
The location of immune cells on the organogram is ambiguous

### ISSUE THREAD

**Issue by ambrosejcarr** [DataBiosphere/data-portal#517]
Immune and Blood being both present on the Organogram is a bit confusing without an explanation of what that means. Looking at the image, I expect "immune" to be _specifically_ "lymphatic system" and "blood" to be anything extracted from blood (both of which will include immune cells, of course). 

I'm not sure if I should expect to find tissue resident immune cells in "immune", "blood", or the relevant tissue that I'm looking for. 

I think this image needs a figure caption to explain how cells were partitioned into organs, given that some cell types will overlap.

**Comment by theathorn** [comment]
See new design as per #478.

**Comment by NoopDog** [comment]
closing the homepage was updated.
