### ISSUE TITLE
It was not apparent that the data portal contains raw data from the explore data splash page

### ISSUE THREAD

**Issue by ambrosejcarr** [DataBiosphere/data-portal#520]
It's my impression that a naive user coming to `data.humancellatlas.org` would not know that we offer non-matrix non-metadata data without substantial exploration. There is no obvious text explaining the availability of, for example, `fastq` or `bam` files unless I click on the "file" drop-down or the "guides" section, which has a guide about `bam` downloads. There is also no mention of raw files or file types on either the main splash page or the browser -- just that the HCA processes such data. 

One possible fix would be to add download icons to individual projects, exactly as has been done for the matrix and metadata, for `fastq` and `bam` files, and changing "export selected data" to "bulk export".

**Comment by theathorn** [comment]
See data-browser/#903 for download of fastq and BAM files.
