### ISSUE TITLE
Add DCP organizational information to the portal

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#563]
@briandoconnor : I think we need to organize additional content to put on the DCP portal.  Think things similar to https://nhlbidatastage.org.

It would be a strategic advantage for us to have the DCP organizational information live on our portal and maintained by, say, Cara or the new comms person.

  - [HCA White Paper](https://drive.google.com/open?id=0BxqPLt03PqkDanNVUjF0cGpYTU0) - Great overview as to why the HCA came to be and an overall introduction
  - [Onboarding](https://docs.google.com/document/d/1VWFWbtQoaKlMQCkD8m8Hl021A0Lyt1qJodXYygiKRrs/edit?userstoinvite=stahiri@broadinstitute.org&ts=5c704c87) - The nuts and bolts of getting all of your accounts set up
  - [Google Website](https://sites.google.com/broadinstitute.org/hca-dcp-org/home) - Builds on the white paper in terms of providing the next layer of details for HCA and goes into the specifics of how we are working to execute the vision of HCA
  - [Project Charters](https://github.com/HumanCellAtlas/dcp-community/tree/master/charters) - These are a great overview of the projects within the HCA. This is one layer down from the details on the website
  - [Science and Development References](https://docs.google.com/document/d/1vcgLT2u0nhQ7U2SI2deBHdrleLt5pD9qpIJOsj2g1VA/edit#heading=h.d99bbgplfmtd) - This doc is a great reference point for new team members for the more technical/scientific side of the work. It helps explain some of the concepts/methods/etc. that are used for HCA
  - [HCA Test Portal](https://prod.data.humancellatlas.org/) - Beta of the portal and is a good way to take all of the reading and put context to it
  - [Google Drive](https://drive.google.com/drive/folders/0B0_BwfsoZLStVG51aU9fQTMwLU0) - This goes beyond an overview and is where the files for HCA within DSP are housed
  - [HCA Project External Contacts](https://docs.google.com/spreadsheets/d/1NRkXxUg40U8RKxcwxobjPXHPCtMllvqt6DXoqdd-gyg/edit#gid=0) - List of external POCs for individual projects

**Comment by NoopDog** [comment]
Obsolete
