### ISSUE TITLE
Pipelines docs URLs have lots of nested layering

### ISSUE THREAD

**Issue by kbergin** [DataBiosphere/data-portal#564]
Is it possible to change the URLs so that there aren’t three layers that just say pipeline over and over? :slightly_smiling_face: 
i.e.:
https://data.humancellatlas.org/pipelines/hca-pipelines/data-processing-pipelines/qc-metrics
https://data.humancellatlas.org/pipelines/hca-pipelines/data-processing-pipelines/optimus-workflow
https://data.humancellatlas.org/pipelines/hca-pipelines/data-processing-pipelines/smart-seq2-workflow

I think it's happening because of the tabbing organization on the page but maybe all the tabs /subcategorizations aren't necessary.

**Comment by NoopDog** [comment]
@kbergin  Hi There, the urls are updated on prod. Can you take a looks and close this if it looks ok?


https://data.humancellatlas.org/pipelines


Thanks,
D

**Comment by kbergin** [comment]
Looks great! Thank you, @NoopDog !
