### ISSUE TITLE
Link pipelines workflows to Dockstore

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#566]
From @briandoconnor : 
FYI from Benedict : “Wondering why on the HCA portal pipelines page we don't link from each workflow to dockstore:” “Also, the project pages on the portal page are kind of nice, it would be great to make the dockstore workflow pages much closer to this in terms of rich description”.

**Comment by NoopDog** [comment]
Obsolete closing

**Comment by NoopDog** [comment]
Obsolete closing
