### ISSUE TITLE
Guides -> Exploring Projects has outdated graphics and text

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#579]

**Comment by MillenniumFalconMechanic** [comment]
@NoopDog, please update the following content:

1. Exploring Projects - the project detail page now also displays Analysis Tools and a citation link.

1. Accessing HCA Data in a Jupyter Notebook - @frano-m has added updated screenshots for this flow, corresponding text now needs to be updated.

**Comment by NoopDog** [comment]
Ok  @MillenniumFalconMechanic 

I left "Exploring Projects" as is.

I updated the 2nd Guide content "Accessing HCA Data in a Jupyter Notebook" and pushed this back to the branch.

Let me know if this looks ok.

Cheers
Dave
