### ISSUE TITLE
Create DCP Strategy page

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#582]
@lauraclarke :  I have been asked to provide information about what the DCP will do in 2020 for the newsletter which is being prepared now. Can we create a page about strategy which we could extend later to give me a URL to link to?

The content is likely to start with something like https://github.com/HumanCellAtlas/dcp-community/blob/master/strategy/overall-aims.md

**Comment by theathorn** [comment]
@lauraclarke Do you want a page with a link to the "overall aims" doc in github or you want to pull-in  the content and edit/re-format for the portal?

**Comment by lauraclarke** [comment]
I think it is better to have the content on the website or at least a summary of the content as I think anything which requires people to follow a link to github would be unlikely to be followed by the majority of readers

**Comment by lauraclarke** [comment]
As a note, the urgency of this has shifted to be needed by early December rather than asap

**Comment by diekhans** [comment]
There are various tools to convert markdown to html.   I don't think it looks very professional to just link end-user documentation to github..

**Comment by NoopDog** [comment]
closing, can revisit with the DCP 2.0 team as required
