### ISSUE TITLE
Update instructions in "Exporting HCA Data to Terra" guide

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#583]
- Terra (or Dockstore) bug: When searching for a workflow in Terra the "wdl" in "https://dockstore.org/search?_type=workflow&descriptorType=wdl&searchMode=files" needs to be uppercase "WDL" or Dockstore needs to become case-insensitive on the search.
  - Select "Process multiple workflows" then "Select Data", "Choose specific rows to process", select one file and click "OK".
  - In the Attribute column select the drs URL (e.g. this.\_\_bam\_\_drs\_url).

**Comment by theathorn** [comment]
@natanlao Do you agree with these changes?  The dockstore-wdl-workflow-md5sum graphic would also need to be updated to reflect the value for Attribute.

**Comment by chmreid** [comment]
Link to guide: https://data.humancellatlas.org/guides/consumer-vignettes/export-to-terra

Link to file: https://github.com/HumanCellAtlas/data-portal/blob/staging/content/guides/userguides/terra-export.md

**Comment by natanlao** [comment]
> Do you agree with these changes? The dockstore-wdl-workflow-md5sum graphic would also need to be updated to reflect the value for Attribute.

The last two changes make sense to me.

> Terra (or Dockstore) bug: When searching for a workflow in Terra the "wdl" in "https://dockstore.org/search?_type=workflow&descriptorType=wdl&searchMode=files" needs to be uppercase "WDL" or Dockstore needs to become case-insensitive on the search.

I am able to reproduce this bug. Do you want me to update the user guide to account for this? This seems like something that should be fixed on Terra's side (and/or Dockstore's side). (@theathorn)

**Comment by theathorn** [comment]
For the WDL/wdl bug @mikebaumann will file the appropriate ticket, so we just need to address items 2 and 3 for this ticket.

**Comment by NoopDog** [comment]
@theathorn this is ready to review on staging.

**Comment by theathorn** [comment]
Change "Select Date" to "Select Data".

Change the image to specify "this.\_\_bam\_\_drs\_url" instead of a fastq URL.

**Comment by NoopDog** [comment]
@chmreid Hi Charles, checking you saw Trevor's comments above. Can you make a new PR with these updates? Thanks!

**Comment by natanlao** [comment]
@NoopDog I'll carry this PR from here. Thanks for picking this up in my absence @chmreid!

**Comment by NoopDog** [comment]
@theathorn your latest requested changes are on staging for your review. Cheers, D

**Comment by theathorn** [comment]
Changes approved.
