### ISSUE TITLE
Add FAQ section for Pipeline

### ISSUE THREAD

**Issue by ekiernan** [DataBiosphere/data-portal#596]
**Why:**
It is not immediately clear where to find specific information on the Pipelines tab of Data Portal. 

**Acceptance Criteria:**
FAQ will address user questions like:
What pipelines are being developed?
Can I ask DCP to make a pipeline for my assay of interest? (make a pipeline request form)
How do I contribute a pipeline?

@matthewspeir

**Comment by NoopDog** [comment]
Obsolete closing

**Comment by NoopDog** [comment]
Obsolete closing
