### ISSUE TITLE
Add Pipeline Version Information to the Pipelines Tab

### ISSUE THREAD

**Issue by ekiernan** [DataBiosphere/data-portal#597]
Why: 
There is currently no documentation of pipeline versions, which might be necessary if a researcher requires this information for publication.  

Acceptance Criteria: Add an overview of where to find pipeline version information to FAQ section and pipelines landing page.

@matthewspeir

**Comment by NoopDog** [comment]
Obsolete closing

**Comment by NoopDog** [comment]
Obsolete closing
