### ISSUE TITLE
create feedback pathway for early users

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-portal#6]
Link to a google form? - Jen

**Comment by happyimadesignr** [comment]
Figuring out zendesk, cany(sp?), etc. What we're using for what kind of feedback and who it'll go to

**Comment by happyimadesignr** [comment]
Zendesk will be from the Help link

**Comment by happyimadesignr** [comment]
@NoopDog Zendesk will be the help link, anything else needed here?
