### ISSUE TITLE
Add Data Browser API to APIs documentation

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#607]
Publish the Azul API used by the Data Browser.

**Comment by theathorn** [comment]
https://dcp2.data.humancellatlas.org/apis/api-documentation/data-browser-api should link to https://service.azul.data.humancellatlas.org/ not https://service.dev.singlecell.gi.ucsc.edu/

**Comment by NoopDog** [comment]
@theathorn this updated on https://dcp2.data.humancellatlas.org/apis/api-documentation/data-browser-api

Cheers,
D

**Comment by theathorn** [comment]
LGTM.
