### ISSUE TITLE
Add a checkbox to filter the display to only required metadata fields

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#609]
Cant find the old issue, creating a new one.

**Comment by mshadbolt** [comment]
Wanted to add here that the aim of this checkbox is to give contributors a filtered view of the fields they would need to provide so it should ignore the required fields that are system generated. 

So by required here we actually mean, 'the contributor is required to provide this value'

**Comment by NoopDog** [comment]
Hi @mshadbolt this is on production. Cheers, D
