### ISSUE TITLE
Remediate High serialize-javascript vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [DataBiosphere/data-portal#620]
Snyk reports the following High severity vulnerability in HumanCellAtlas/data-portal. Please remediate by the end of Q1 Milestone 2.

**Description**
serialize-javascript

**Suggested Remediation**
Upgrade serialize-javascript to version 2.1.1 or higher.

**Details**
serialize-javascript is a package to serialize JavaScript to a superset of JSON that includes regular expressions and functions. Affected versions of this package are vulnerable to Cross-site Scripting (XSS). It does not properly sanitize against unsafe characters in serialized regular expressions. This vulnerability is not affected on Node.js environment since Node.js's implementation of RegExp.prototype.toString() backslash-escapes all forward slashes in regular expressions.

**Comment by NoopDog** [comment]
@theathorn requesting permission to do security updates for the data-portal.

**Comment by NoopDog** [comment]
@Lilalamar the fix for this is deployed to prod. This should resolve the alert. Please re-open if you find this is still a problem.  Cheers, D

**Comment by Lilalamar** [comment]
@NoopDog thank you!!
