### ISSUE TITLE
Add "r" release documentation section and sub document stubs to portal

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#625]

**Comment by gabsie** [comment]
Hi, @NoopDog  - adding some exploration sketches of the release page and the project page, which are ideas only. Happy to discuss them, they're in no way final etc.

![IMG_project](https://user-images.githubusercontent.com/19713125/73950295-99a1ec00-48f3-11ea-8570-5c199ffd4353.jpg)
![IMG_release](https://user-images.githubusercontent.com/19713125/73950305-9c9cdc80-48f3-11ea-8725-83b5311a5498.jpg)

Thanks, Gabby
