### ISSUE TITLE
Home Page Search Bar

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#64]

**Comment by happyimadesignr** [comment]
@NoopDog this is the example for no results ![Screen Shot 2018-06-25 at 4.06.55 PM.png](https://images.zenhubusercontent.com/5ab9846b4b5806bc2bcc80e2/ac07f56e-5364-4391-b2ba-ac797609b124)

**Comment by theathorn** [comment]
Needs to convert to auto-complete.
