### ISSUE TITLE
Populate "Attributions" page with contributor info

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#647]
Sections for 

## DCP Release Contributors 
Those who helped annotate and wrangle the release. 

Grouped by Project Title then [Name, Institution]

**Comment by theathorn** [comment]
@lauraclarke suggests Project Title then [Name, Institution].

Order alphabetically by Project Title and then Name.

**Comment by NoopDog** [comment]
@MillenniumFalconMechanic lets discuss how to do this  for the included projects. Perhaps its worthwhile to do this programmatically even if its just a script we run to print out the names and then dump them in the markdown file manually.
