### ISSUE TITLE
"Working with Release Files" has many broken links

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#648]
These links get a "404 - page not found":
  - 2020-Mar-Landscape-Adult-Liver-10x
  - March 2020 Release Methods
  - analysis tutorial
  - Community Feedback Page

Please check all of the links in this page..

**Comment by NoopDog** [comment]
Hi Liz, to link to the browser and use the appropriate environment ( staging, prod, dev etc) you can use the following custom tag:

`<link-to-browser relativelink="/releases/2020-mar">March 2020 Data Release</link-to-browser>`

For  an example of this see the overview page markdown:
https://raw.githubusercontent.com/HumanCellAtlas/data-portal/ux-dev/content/releases/2020-mar/overview.md

Let me know if you this makes sense. You just replace the value of the “relativelink” attribute with the browser url you want.

**Comment by ekiernan** [comment]
I think all links have been fixed for this doc!

**Comment by theathorn** [comment]
@ekiernan The 2020-Mar-Landscape-Adult-Liver-10x links (there are two) just go to the main Data Browser explore page, not to the release files for that dataset.

@MillenniumFalconMechanic Also the "Improve this page" at the bottom gets a "404 - page not found" error.

**Comment by NoopDog** [comment]
The improve this page link will work once this is deployed to staging. Currently its on ux-dev only.

**Comment by ekiernan** [comment]
@NoopDog Would this be correct relative link for the liver dataset: relativelink="/projects/4d6f6c96-2a83-43d8-8fe1-0f53bffd4674/m/releases/2020-mar/datasets/2020-Mar-Landscape-Adult-Liver-10x/release-files"

**Comment by ekiernan** [comment]
Success!! Ok, I think now the links are working.

**Comment by theathorn** [comment]
There's still an issue with the second "2020-Mar-Landscape-Adult-Liver-10x" link just above the "Pegasus" section title.

**Comment by ekiernan** [comment]
Ok, I just updated that one.

**Comment by theathorn** [comment]
Looks good.
