### ISSUE TITLE
Fix broken links on release overview page

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#649]

**Comment by NoopDog** [comment]
@ekiernan I have adjusted the links on the overview page and they seem to be working. Can you confirm? Thanks!

**Comment by ekiernan** [comment]
Hi Dave, 

It still looks like the Smart-seq2, Methods, working with release files, tutorial, and feedback are links are broken. I tried playing with them a couple of times yesterday, but nothing was working.

**Comment by ekiernan** [comment]
Looks like they are working!
