### ISSUE TITLE
Release - "Improve this page"

### ISSUE THREAD

**Issue by TimothyTickle** [DataBiosphere/data-portal#652]
## Expected behavior
When you click on the "Improve this page" at the bottom of the Release documentation pages it does not 404 (one example is https://ux-dev.data.humancellatlas.org/releases/2020-mar/acknowledgements but this happens on all the pages I checked).
## Actual behavior
It 404s
## Steps to reproduce the behavior
Click on the "Improve this page" link at the bottom of https://ux-dev.data.humancellatlas.org/releases/2020-mar/acknowledgements

**Comment by theathorn** [comment]
@NoopDog  Will this will be fixed by promoting from the ux-dev to prod environments?

**Comment by NoopDog** [comment]
Yes, once this is in staging the links will work.

**Comment by NoopDog** [comment]
Yes, once this is in staging the links will work. Closing
