### ISSUE TITLE
Update "Contributors" information in Mar-2020 "Acknowledgements" section to be consistent with the SCP

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-portal#661]
To maintain consistency between SCP and HCA Data Portal for the March release, please update the following Contributor's roles:

In this dataset: https://data.humancellatlas.org/explore/projects/4d6f6c96-2a83-43d8-8fe1-0f53bffd4674
In Contributors:
Jeff C Liu (Clinician) change to Jeff C Liu (Computational scientist)
Brendan T Innes (Clinician) change to Brendan T Innes (Computational scientist)

In this dataset:
https://data.humancellatlas.org/explore/projects/c4077b3c-5c98-4d26-a614-246d12c2e5d7
In Contributors:
Sarah A Teichmann (Principal Investigator) change to Sarah A Teichmann (Co-investigator)

**Comment by theathorn** [comment]
Need to update the corresponding entries in https://ux-dev.data.humancellatlas.org/releases/2020-mar/acknowledgements.

Note: the "Contributors" sections in the Project pages listed above will still be incorrect since they are populated directly from the ingested metadata files.

**Comment by zperova** [comment]
@theathorn thanks, yes, I understand that everything pulled from the metadata will remain as is. Didn't have time/access to pull the correct ux-dev links for this.
