### ISSUE TITLE
"March 2020 Release" disappears from top nav unless "explore" tab is selected

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#662]
Click on "documentation" link in the "Mar 2020 Release" page and the "Mar 2020 Release" disappears from the top  nav bar.

In fact, it's only present when the "explore" tab is selected?? It doesn't appear when the home page or any other top nav item is selected.

**Comment by NoopDog** [comment]
Sorry, yes we just broke this. Fixing.

**Comment by theathorn** [comment]
This is fixed for the data portal.
