### ISSUE TITLE
Revisit Versions of Jumbotron (Cell) Image Optimized for Device Sizes

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-portal#68]

**Comment by happyimadesignr** [comment]
@frano-m I replaced the images in the sketch file with the purchased image. And there is an example for mobile. Can you use the updated image, it's better quality. Do you need anything else from me?

**Comment by frano-m** [comment]
@happyimadesignr new image in place + Hero H1 implemented for screens > 768px
