### ISSUE TITLE
APIs - Update API documentation to indicate the APIs that will be deprecated in DCP/2

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#680]
https://data.humancellatlas.org/apis:
  - The Data Store API will not be supported in DCP/2 - the API used by the Data Browser will be published.
  - The Matrix Service API will not be updated for the data in DCP/2 - please contact us with your needs for this service.

**Comment by NoopDog** [comment]
@theathorn the DSS and Matrix APIs are marked as deprecated on staging:

https://staging.data.humancellatlas.org/apis/api-documentation/matrix-service-api
https://staging.data.humancellatlas.org/apis

If this looks ok, we can deploy.

Ingest is not being deprecated so left that as is.

**Comment by theathorn** [comment]
Looks OK to me.
