### ISSUE TITLE
Announcement on DCP/1 of changes that will be introduced with DCP/2

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#681]
Add an "Announcements" / "Coming soon - DCP v2" banner on the home page.
Add an  "Announcements" page that gives an overview of changes coming for DCP/2, including links to deprecated APIs.

**Comment by NoopDog** [comment]
@theathorn can we get the text for 

>Add an "Announcements" page that gives an overview of changes coming for DCP/2,

**Comment by theathorn** [comment]
Please promote https://staging.data.humancellatlas.org/coming-soon-DCP-2-with-support-for-controlled-access-data to DCP/1 prod today. Do not link to it from any other pages (i.e. no banner).  Kathleen will then send an email to the community, including the link.

**Comment by NoopDog** [comment]
https://data.humancellatlas.org/coming-soon-DCP-2-with-support-for-controlled-access-data

@theathorn this is promoted note the prod url.

**Comment by MillenniumFalconMechanic** [comment]
https://docs.google.com/document/d/1Mo1cEEpjeKs8wViMTcMdLJVL44Lz7BWo_HSbWbDmLFg/edit
