### ISSUE TITLE
Check if "Contributing Pipelines" page is still valid concept or if is done differently

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#689]
Are we still accepting pipelines to be contributed to the HCA as descried here:
https://data.humancellatlas.org/contribute/analysis-pipelines

```Data modalities to be analyzed in the HCA DCP Green Box are chosen by the Data Coordination Platform Governance Group (DCPGG). Pipelines for these modalities are included for use in the HCA DCP after they have been evaluated and approved by the HCA Analysis Working Group. The evaluation includes portability testing of the candidate pipeline using the Portability Service.

The service sends the candidate pipeline definition and the test input data to one or multiple external execution infrastructures, which run the pipeline and send the results back for comparison to the expected results using the evaluation tool provided by the pipeline developer.

If you are interested in submitting a pipeline for evaluation, please contact us at data-help@humancellatlas.org.
```

We should at least remove references to "green  box", but I am also checking if the  "Pipeline Portability Service" is being deprecated or has a new model as  we will be using Terra to run the alignment and expression processes..

@ekiernan @kbergin can you weigh in on this or let me know who the right person to reach out to is?

Thanks,
D

The

**Comment by kbergin** [comment]
@NoopDog we don't currently have an approved process or system for this, but when we finish revamping to DCP2.0, people could "byo pipelines" via Terra, so we'll want to elaborate on how to do that later. I'd say remove for now.

**Comment by NoopDog** [comment]
Thanks  @kbergin, will do.

**Comment by NoopDog** [comment]
Thanks will mark this as remove for 2.0.
