### ISSUE TITLE
Remove links to dcp-feedback repo

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#722]
The [feedback page](https://data.humancellatlas.org/feedback) has links to the [dcp-feedback repo](https://github.com/HumanCellAtlas/dcp-feedback/) via the "bug report" and "suggest an idea" links.

These should be removed as this repo is no longer monitored - all user feedback should be channeled through the HCA ZenDesk.

**Comment by NoopDog** [comment]
@theathorn  this is on staging for review. 

https://staging.data.humancellatlas.org/feedback

**Comment by theathorn** [comment]
Looks good.
