### ISSUE TITLE
Privacy - EBI: Update GDPR Privacy notice for DCP/2 MVP

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#734]

**Comment by NoopDog** [comment]
@theathorn I believe this can be closed too?

**Comment by theathorn** [comment]
I will get the new EBI GDPR statement from Tony.

**Comment by NoopDog** [comment]
Is there one for Broad then too and shall we list all three on the site?

**Comment by theathorn** [comment]
https://www.ebi.ac.uk/data-protection/privacy-notice/embl-ebi-public-website

**Comment by theathorn** [comment]
Tony says we don't need a GDPR statement on the data portal for EBI.
If someone contacts (emails) EBI for submission, then they receive a privacy statement at that point.
