### ISSUE TITLE
Data Use Agreement  -  Update Data Set License and Data Set Policy for DCP2

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#746]
https://data.humancellatlas.org/about/data-use-agreement

**Comment by lauraclarke** [comment]
So I think for MVP, this is fine as is
That said we do need to look at this post MVP as we shouldn't relicense datasets we have imported from GEO or ArrayExpress with a different set of terms than come from their own service but I think that is a more complex issue than can be done in time for I think for MVP this is sufficient

**Comment by NoopDog** [comment]
@theathorn can we close this based on the comments above?

**Comment by lauraclarke** [comment]
This shouldn't stop the ticket being closed but as an FYI, was in a recent conversation with people from the Ethics working group and they are drafting an open data use agreement for all HCA data which once it becomes final we should adopt. I will let you know if/when I hear more but if you can also keep an eye out that would be great

**Comment by theathorn** [comment]
@NoopDog If we are not changing anything for the DCP/2 MVP, perhaps we should move this ticket into the backlog and use it to monitor for a new data use agreement from the HCA Ethics WG.

**Comment by NoopDog** [comment]
Can we use (and close)  this ticket to note that we have done the review and make a new one for the ethics review etc... ?

**Comment by theathorn** [comment]
Created #782 and closing this ticket as complete.
