### ISSUE TITLE
Contribute - Review "Contributing Data" Section

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#749]
This is for the "Contributing Data" section under the contribute tab.

https://data.humancellatlas.org/contribute

**Comment by lauraclarke** [comment]
Just to confirm, what URL/markdown should we be reviewing?

**Comment by NoopDog** [comment]
I updated the description above to indicate  https://data.humancellatlas.org/contribute

**Comment by NoopDog** [comment]
ok for go live of MVP
