### ISSUE TITLE
Deepbody Analytica

### ISSUE THREAD

**Issue by Deepbody-me** [DataBiosphere/data-portal#753]
Thank you for submitting a portal to the HCA DCP Methods Registry!

To expedite your portal's addition to https://data.humancellatlas.org/analyze,
please provide the following package metadata.  You can easily edit this information later by clicking "Improve this page" at the bottom of your portal's detail page ([example](https://data.humancellatlas.org/analyze/portals/asap)).

Required:
- Tool title: President 
- Contact name: Vladimir Lialine 
- Contact email: vlad@deepbody.me 
- Who to attribute: Deepbody Inc &  Vladimir Lialine
- Portal URL: https://deepbody.me/humancell
- Short description: (<= 200 characters, will appear on list page) Computational analysis of Human Cells interactions. 
Optional:
- Long description: (will appear on detail page)
- Logo or screenshot: (attach to this GitHub issue.)

**Comment by NoopDog** [comment]
@Deepbody-me Thank you for submitting the request to add Deepbody Analytica portal to the HCA methods registry. 

Would you be able to add:

1.  A detailed description of the project including the type(s) of analysis performed and the data types processed.

1. A a link to the projects github repository?

1. A screenshot

**Comment by Deepbody-me** [comment]
We provide these services on Demand, any Data Types.
Any analysis on-demand.
The Data is not ours.. We provide  tools, Data Pipelines as a service.
Projects are NDAs..

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by NoopDog** [comment]
@Deepbody-me we do not have enough information to process your request so we will close this ticket. Feel free to resubmit if would like in the future. Please take a look at the requested information, and also the other portals and tools on the site to get an idea of the content needed for successful submission.  Feel free to reach out with any questions.

Cheers and Thanks,
Dave Rogers
