### ISSUE TITLE
HCA Ethics Working Group update to the Data Use Agreement

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#782]
@lauraclarke "I was in a recent conversation with people from the Ethics working group and they are drafting an open data use agreement for all HCA data which once it becomes final we should adopt. I will let you know if/when I hear more but if you can also keep an eye out that would be great".

**Comment by theathorn** [comment]
Likely to be updated as part of the managed access  work.

**Comment by MillenniumFalconMechanic** [comment]
Re-open when we hear from Ethics WG.
