### ISSUE TITLE
Finalise Approach on Typography.JS vs Roll Our Own

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-portal#82]

**Comment by MillenniumFalconMechanic** [comment]
@happyimadesignr We are looking at using Typography.js, which has a tight typography specification using concepts such as vertical rhythms (see https://www.smashingmagazine.com/2009/04/8-simple-ways-to-improve-typography-in-your-designs/#4-vertical-rhythm). 

Do you have an opinion on this? It looks like this might be a best practice that people are moving towards (for example, the Gatsby community is using Typography.js heavily). And if it something we could use, would it require updates to your typography spec, or are you using vertical rhythms etc already?

**Comment by happyimadesignr** [comment]
Ultimately I want to end up with our visual design. You can use it to start and then adjust it to our designs, if that works. Up to you @MillenniumFalconMechanic
