### ISSUE TITLE
Link to examples created for Analysis Tools API demo 

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#835]
The notebook shows how to download all matrices from a project. https://github.com/DataBiosphere/azul/blob/develop/docs/download-project-matrices.ipynb

The command-line script can do a couple of things such as download matrices or request a curl-format manifest https://github.com/DataBiosphere/azul/blob/develop/docs/hca_file_downloader.py

**Comment by NoopDog** [comment]
@theathorn @danielsotirhos staging is updated with links to the code developed for the analysis tools demo for your review.
https://dev.singlecell.gi.ucsc.edu/apis/api-documentation/data-browser-api

Cheers, D

**Comment by dsotirho-ucsc** [comment]
"API Usage Examples" section looks good. Approved.

**Comment by NoopDog** [comment]
Thanks, @danielsotirhos
