### ISSUE TITLE
Adding a contributor's portal to the data browser project page

### ISSUE THREAD

**Issue by mshadbolt** [DataBiosphere/data-portal#843]
## User story

* As a contributor I want the analysis portal that I created to show in the list of Analysis Portals on my project page so that users who are interested in my study know they can access it

We have had some feedback that a contributor would like their own portal to appear in the browser in the 'Analysis portals' section. 

The specific project is here: https://data.humancellatlas.org/explore/projects/f2fe82f0-4454-4d84-b416-a885f3121e59/external-resources?catalog=dcp2

The link to their portal is currently a supplementary link, but it could be more accurately described as an analysis portal. Is there any way for contributors to specify their own analysis portals or is the 'Analysis portal' section only for other broader portals like SCEA, cell browser etc?

**Comment by NoopDog** [comment]
Hi @mshadbolt Yes, I think this could fit in with the portal registration system that we were making progress on before the re-org. @theathorn we could possibly start up with the manual registrations that we used to do Xena and Single Cell Portal etc. @mshadbolt we need to see what it would take to re-enable this and prioritize etc.

**Comment by theathorn** [comment]
@mshadbolt Are all "Supplementary Links" "Analysis Portals", and if not, can "regular supplementary links" be distinguished from "analysis portal supplementary links" in the metadata? I'd rather leverage this info being supplied by contributors in a standard way via metadata rather than forcing them through the more complex Portals Registration API.

**Comment by mshadbolt** [comment]
@theathorn yes I was having the same thoughts. Unfortunately, at the moment we don't have a way to distinguish the different kinds of links, the supplementary links field is quite a grab bag of things. 

Perhaps we could consider having typed links in our schema, e.g. github links would be 'code_links' analysis portal links would be 'analysis_portal_links'. In theory, would the browser then be able to support showing those in the appropriate categories?

**Comment by theathorn** [comment]
Does "typed links" sounds like a reasonable approach @hannes-ucsc and @NoopDog ?

**Comment by NoopDog** [comment]
Yea typed links sound good. These types would be specified in the metadata schema I presume?  As long as we have the categories in the Azul product API response then yes we can signify the different link types on the UI.

**Comment by NoopDog** [comment]
Obsolete, closing
