### ISSUE TITLE
Request to add MiCV to the portal registry

### ISSUE THREAD

**Issue by sylviamic** [DataBiosphere/data-portal#845]
Hi there! We'd love to see MiCV added to your analysis portal registry, if at all possible.

Required:
- Tool title: MiCV - a Multi-informatic Cellular Visualization tool
- Contact name: Nigel Michki
- Contact email: nigelmic@micv.works
- Who to attribute: Michki, Nigel S.; Cai, Dawen; Walker, Logan A.
- Portal URL: https://micv.works
- Short description: MiCV is the simplest single-cell RNA-seq analysis tool you'll find anywhere on the web. Upload data in a variety of standard formats, click one button, and you're done - really. Built on top of scanpy and other open source tools, MiCV makes it possible to access best-in-class analysis without having to be a best-in-class analyst.

Optional:
- Logo or screenshot: (see attached)
![MiOmics_logo_blue_grey_icon_v1](https://user-images.githubusercontent.com/5039366/105792626-bc3e7200-5f55-11eb-8ce0-04cc67475b15.png)

Thank you for your consideration and for managing such a remarkable project! Please let me know if there's anything I can do to help this along.

**Comment by NoopDog** [comment]
@nigeil Thank you for submitting the request to add MiCV to the HCA Methods Registry. Would you be able to provide additional text / background e.g. a long description and a screenshot?

Would be great if we can take a look at what kinds of input files are processed, what kinds of analysis is done and what makes this tool unique.

Thank you!

**Comment by NoopDog** [comment]
Hi @nigeil I am closing this ticket as we have not received a response to the above questions. Feel free to reopen if you would like to provide the requested additional information. 

Cheers and Thanks,
Dave Rogers
