### ISSUE TITLE
Tech Design/Feasibility for using URL Path instead of Sub Domain for Different Apps within the Site.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#85]

**Comment by theathorn** [comment]
e.g. data.humancellatlas.org/explore instead of explore.data.humancellatlas.org.
I will contact CZI DevOps, Sam Pierson and Parth Shah.

**Comment by theathorn** [comment]
From Sam:
Undecided.  Given all our apps are on different stacks developed by different teams, separate sub-domains is easier.  If however, your team would like to develop the reverse proxy / webserver configuration that support paths proxying to a bunch of different services, that would be excellent!

**Comment by theathorn** [comment]
Makes sense to keep each App in it's own sub-domain (e.g. Contribute, Explore, etc.).
e.g. [app].data.humancellatlas.org or data.humancellatlas.org/build for now.

Stretch goal for Summer Pilot: move Apps under main domain. e.g data.humancellatlas.org/contribute.

**Comment by theathorn** [comment]
From PM meeting: this was not regarded as a critical issue and any implementation would fall on the Portal team. So I think this goes to the Backlog.

**Comment by theathorn** [comment]
When you select the "Explore" tab then the (Chrome) browser tab loses its little mosaic circle logo (it didn't use to).
