### ISSUE TITLE
Resolve SSR bundle failed errors during gatsby build

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-portal#866]
We are getting the following errors during build:

![7db900b8-0b13-42e2-b5b6-3a420bb5606b.png](https://images.zenhubusercontent.com/57339587bf93871ccd9ae22c/a4c32e93-5a9d-48a9-bf99-8d1ba9339512)

This issue is said to be resolved in `gatsby@2.32.3` (see [Gatsby issue](https://github.com/gatsbyjs/gatsby/issues/29326)) but we are still seeing the error in `gatsby@2.32.7`.

I have added `@babel/plugin-transform-spread@7.12.1` as a dev dependency to rely on npm to dedupe this dependency at `7.12.1` (which fixes the issue).

To do: investigate the purported fix in `gatsby@2.32.3` and determine why we're still seeing the error in `2.32.7`. 

**Note, once resolved, `@babel/plugin-transform-spread@7.12.1` is to be removed from the dev dependencies.**

**Comment by NoopDog** [comment]
obsolete, closing
