### ISSUE TITLE
Work with Data Store Service to Pull Dev Docs

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#89]

**Comment by happyimadesignr** [comment]
https://docs.google.com/document/d/1c8XdfBxMfsOoUJ6wqjOCTiIXYecgzLFFmar-oDBvPpM/edit?usp=sharing

**Comment by theathorn** [comment]
Is this the same as #75?

**Comment by NoopDog** [comment]
DSS is sunset for HCA no longer required
