### ISSUE TITLE
Health check endpoints

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-portal#9]
As an administrator I would like to be able to discover if the site is up by issuing a simple health check call.

This corresponds to Level 1 in Rex's Health check doc here:
https://docs.google.com/document/d/15dGnWzMH3tpc5zCBLf0KiIvFh8lJvjGw9urT54XhFL4/edit#

the Endpoint should be /health and it should return 200 if the system is running. Note that this is not meant to be a thorough health check, just a basic ping.

Required for Go-Live

**Comment by theathorn** [comment]
Ask #dcp-ops for advice @NoopDog

**Comment by NoopDog** [comment]
Ok Reached out to Mat W for help with this.

**Comment by theathorn** [comment]
From Matt Weiden in DataBiosphere/azul#258:

To make the System Availability tab work for https://humancellatlas.github.io/ you need a route53 health check preferably configured here https://github.com/HumanCellAtlas/dcp-monitoring.
Should take <1 hour to implement.

You could use cloudwatch metrics to generate your availability report.
Whatever strategy you devised there could be reused across all components.
Here’s some sample code https://gist.github.com/mweiden/035979ee28a000e48cc655058c6e1a73

**Comment by theathorn** [comment]
See https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/README.md

**Comment by theathorn** [comment]
Superseded by #311.
