### ISSUE TITLE
Slurp "Read the Docs" Auto Docs

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#90]

**Comment by kozbo** [comment]
https://hca.readthedocs.io/en/latest/
https://github.com/HumanCellAtlas/dcp-cli/blob/master/docs/Makefile

make docs => html

make docs text   ==> makes docs in  .rst format

is it possible to get markdown or JSON? 
does support restructured text.

trent == tsmith12

Can use pandoc to convert???

**Comment by theathorn** [comment]
Obsolete DCP/1 issue.
