### ISSUE TITLE
Add estimated turnaround time to analysis portal submission page

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#917]
https://data.humancellatlas.org/contribute/analysis-tools-registry

Add something along the lines of "The approximate time frame from submission to publication of a new portal is 2-4 weeks".

**Comment by NoopDog** [comment]
@theathorn This on staging here:
https://dev.singlecell.gi.ucsc.edu/contribute/analysis-tools-registry

**Comment by theathorn** [comment]
LGTM
