### ISSUE TITLE
Rename references to pipelines to remove HCA as this implies endorsement

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#924]
Scan the pipeline documentation pages on the browser to look for opportunities to update the wording? Namely to remove calling them "HCA" and to be more inclusive to the possibility of community pipelines becoming part of the DCP standard analysis offerings.

**Comment by ekiernan** [comment]
Suggested change to DCP Matrix Description is:
"DCP Generated Matrices are those produced with standardized pipelines approved by the HCA Analysis Working Group. All DCP Generated Matrices include quality control metrics."
