### ISSUE TITLE
Mock for Drop Down Open State

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#93]
![Screen Shot 2018-06-06 at 10.04.33 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/02406655-e99a-431f-b858-28317bdef734)

Need a mock for this guy when open.

Should be similar to the one in the browser but without the counts.

**Comment by happyimadesignr** [comment]
![Screen Shot 2018-06-08 at 3.42.54 PM.png](https://images.zenhubusercontent.com/5ab9846b4b5806bc2bcc80e2/ac026753-b877-4364-9843-d72932ef7661)

**Comment by happyimadesignr** [comment]
Here is the mock!

**Comment by happyimadesignr** [comment]
Also in Abstract
