### ISSUE TITLE
Confirm OLS iri search parameter value for each ontology id curie.

### ISSUE THREAD

**Issue by frano-m** [DataBiosphere/data-portal#941]
For example: `HCAO/GO:0007049` has the iri param `http://purl.obolibrary.org/obo`.

See https://www.ebi.ac.uk/ols/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo/GO_0007049.

Currently we have the following mappings:

"DATA": "http://edamontology.org",
"EFO": "http://www.ebi.ac.uk/efo",
"FORMAT": "http://edamontology.org",
"OBO": "http://purl.obolibrary.org/obo"

We default to OBO "http://purl.obolibrary.org/obo" if there is no match.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
