### ISSUE TITLE
Home Page "Stay up to date" links to Registration Form

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#95]
Can we move this to mid Summer release or do we need this for the F2F?

**Comment by happyimadesignr** [comment]
@NoopDog @theathorn where did we leave off with this again?

**Comment by NoopDog** [comment]
Remove for June F2F as there is no owner for the list yet and no list

------------------------------
Dave Rogers
Partner, Clever Canary
646-286-5371
http://clevercanary.com

@CleverCanary
@_DaveRogers
https://www.linkedin.com/pub/dave-rogers/0/90/92


On Jun 9, 2018, at 9:23 AM, Jennifer Tang <notifications@github.com> wrote:

@NoopDog <https://github.com/NoopDog> @theathorn
<https://github.com/theathorn> where did we leave off with this again?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/HumanCellAtlas/data-portal/issues/95#issuecomment-395917939>,
or mute the thread

**Comment by theathorn** [comment]
"Stay up to date with the HCA Data Portal" on main page.
Adds email to a subscription list.

What happens when you press "Submit"?

**Comment by theathorn** [comment]
From PM meeting: For Pilot, send a message to Zendesk containing "Full name" and "Email address".

**Comment by happyimadesignr** [comment]
![Screen Shot 2018-06-14 at 4.49.00 PM.png](https://images.zenhubusercontent.com/5ab9846b4b5806bc2bcc80e2/4667bf59-42c5-487e-bf89-8e8426763cea)@frano-m link it to this https://www.humancellatlas.org/joinHCA
