### ISSUE TITLE
Publish dcp6 catalog release notes 

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#954]

**Comment by ekiernan** [comment]
Template for Release 6 notes here: https://docs.google.com/document/d/1CC7UG7OyVQVCIwEwZ3VZQapB2b8oTzCO_ODY7rFex8M/edit

**Comment by ekiernan** [comment]
PR is here: https://github.com/HumanCellAtlas/data-portal/pull/980
